### ISSUE TITLE
Injector not found?

### ISSUE THREAD

**Issue by Zilacon** [SBPrime/AsyncWorldEdit#101]
I am using the latest release build on the github releases. And i am using the last successful build of world edit #3370 on world edit's repo.

When the server starts i get this error:
````
[15:08:31 INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v2.2.1
[15:08:32 INFO]: [AsyncWorldEdit] Error loading strings file, using internal fallback.
[15:08:32 INFO]: [AsyncWorldEdit] BlocksHub plugin not found.
[15:08:32 INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix
[15:08:32 INFO]: [AsyncWorldEdit] AsyncWorldEditInjector plugin not found, trying to initialize using static instances...
[15:08:32 INFO]: [AsyncWorldEdit] ***********************************
[15:08:32 INFO]: [AsyncWorldEdit] AsyncWorldEditInjector not found.
[15:08:32 INFO]: [AsyncWorldEdit] ***********************************
[15:08:32 INFO]: [AsyncWorldEdit] * Exception: java.lang.NoClassDefFoundError
[15:08:32 INFO]: [AsyncWorldEdit] * Error message: org/primesoft/asyncworldedit/injector/core/InjectorCore
[15:08:32 INFO]: [AsyncWorldEdit] * Stack: 
[15:08:32 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditMain.getAWEInjector(AsyncWorldEditMain.java:441)
[15:08:32 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditMain.onEnable(AsyncWorldEditMain.java:225)
[15:08:32 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[15:08:32 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[15:08:32 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[15:08:32 INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:463)
[15:08:32 INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:397)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:383)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:357)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:313)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:192)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469)
[15:08:32 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[15:08:32 INFO]: [AsyncWorldEdit] ***********************************
[15:08:32 ERROR]: Error occurred while enabling AsyncWorldEdit v2.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/base/BaseClassFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_79]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:73) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	at org.primesoft.asyncworldedit.AsyncWorldEditMain.onEnable(AsyncWorldEditMain.java:226) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:463) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:397) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:383) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:357) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:313) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:192) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
Caused by: java.lang.ClassNotFoundException: org.primesoft.asyncworldedit.injector.classfactory.base.BaseClassFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[MineTick.jar:git-Bukkit-1.7.9-R0.2-145-gd2daa42]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	... 27 more
````

**Comment by SBPrime** [comment]
Did you install the plugin correctly? You need the AWE injector plugin.

**Comment by Zilacon** [comment]
I did not see that in the 2.2.1 release. Can i get a link?

**Comment by SBPrime** [comment]
From the release: "To update you need to put all the necessary files from AsyncWorldEdit release 2.2.0 and update the AsyncWorldEdit.jar to 2.2.1. "

You can find all the releases here:
https://github.com/SBPrime/AsyncWorldEdit/releases/

Starting from 2.2.0 you need to take manually all the newest parts of the AWE from different versions.

**Comment by SBPrime** [comment]
Not confirmet, Works for me.
