### ISSUE TITLE
PlotMe Update

### ISSUE THREAD

**Issue by MarkusAV** [SBPrime/AsyncWorldEdit#108]
PlotMe is updated and all WorldEdit code is pretty much entirely changed.
We've done tests with the new version of PlotMe (soon to be released, again) - this spams the console: http://hastebin.com/ujezowulus.avrasm

You might already know about it, but just a heads up if you don't. Cheers.

**Comment by MattBDev** [comment]
He is running a Spigot 1.8.3 server with Plotme 0.17.1

**Comment by SBPrime** [comment]
@MattBDev I made a commend on your commit, you might find it useful.

This:

    02.07 22:08:25 [Server] INFO at com.worldcretornica.plotme_core.bukkit.PlotWorldEditListener.worldEditListener(PlotWorldEditListener.java:25) ~[PlotMe-Core.jar:?]
    02.07 22:08:25 [Server] INFO Caused by: java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to com.sk89q.worldedit.bukkit.BukkitWorld

Looks like a bug in Plotme 0.17, in 0.17.1 I do not see the line of code that could cause the error.

When using Plotme 0.17.1 I get:

    Caused by: java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.entity.PlayerWrapper cannot be cast to com.sk89q.worldedit.bukkit.BukkitPlayer
        at com.worldcretornica.plotme_core.bukkit.PlotMeWorldEdit.<init>(PlotMeWorldEdit.java:32) ~[PlotMe-Core.jar:?]
        at com.worldcretornica.plotme_core.bukkit.PlotWorldEditListener.worldEditListener(PlotWorldEditListener.java:37) ~[PlotMe-Core.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[WorldEdit.jar:?]
        ... 44 more

The **Actor** class has **isPlayer()** and **getUniqueId()**. 

Please verify that the stack that you provided is correct.

**Comment by MattBDev** [comment]
I fixed this in my latest commit. Should fix any compatibility issues.

**Comment by SBPrime** [comment]
Great to hear.
