### ISSUE TITLE
AWE Will not work with Forge/Bukkit World Edit

### ISSUE THREAD

**Issue by Zilacon** [SBPrime/AsyncWorldEdit#114]
I am trying to get AWE to work with WE Forge and everytime i do a command with AWE it throws a error.

AWE 2.2.2
WE 6.1 Forge
WE 6.1 Bukkit
KCauldron Build 150 1.7.10

````
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v2.2.2
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * CLASS INJECTION FAILED!! *
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * AsyncWorldEdit won't work properly.
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * Exception: java.lang.NoSuchMethodError
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * Error message: com.sk89q.worldedit.EditSession.ForceClassLoad()Ljava/lang/Class;
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * Stack:
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:132)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:88)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.world.World.<init>(World.java:360)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.world.WorldServer.<init>(WorldServer.java:158)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] * java.lang.Thread.run(Unknown Source)
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] ****************************
[13:36:26] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled
````

````
[13:37:33] [Server thread/INFO]: Zilacon issued server command: //
[13:37:33] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[BindingHelper.class:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220) ~[ParametricCallable.class:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[SimpleDispatcher.class:?]
	at org.primesoft.asyncworldedit.worldedit.utils.command.DispatcherWrapper.call(DispatcherWrapper.java:119) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:225) [CommandManager.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [MethodEventHandler.class:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [EventHandler.class:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [EventBus.class:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [EventBus.class:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.jar:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-1448.121]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalAccessError: tried to access method com.sk89q.worldedit.EditSession.<init>(Lcom/sk89q/worldedit/util/eventbus/EventBus;Lcom/sk89q/worldedit/world/World;ILcom/sk89q/worldedit/extent/inventory/BlockBag;Lcom/sk89q/worldedit/event/extent/EditSessionEvent;)V from class com.sk89q.worldedit.EditSessionStub
	at com.sk89q.worldedit.EditSessionStub.<init>(EditSessionStub.java:58) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.<init>(ThreadSafeEditSession.java:198) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession.<init>(AsyncEditSession.java:101) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:128) ~[?:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:867) ~[LocalSession.class:?]
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:102) ~[WorldEditBinding.class:?]
	... 32 more
````

Am i using the wrong version? Or is this a bug that can be fixed?
Am i supposed to have World Edit for Bukkit while i have World Edit for Forge on the server? I have never messed with WE Forge so that may be messing it up, not sure.

**Comment by SBPrime** [comment]
99% that you installed the plugin incorrectly. Check this tutorial for info:
https://www.youtube.com/watch?v=mTUIZFfu8uk
