### ISSUE TITLE
Error on Spigot 1.9.2 Using Java 8

### ISSUE THREAD

**Issue by TheIntelloBox** [SBPrime/AsyncWorldEdit#124]
[21:45:49] [Server thread/ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@23c4a840 to handler EventHandler{priority=NORMAL}

java.lang.reflect.InvocationTargetException
 at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerCommandPreprocess(WorldEditListener.java:96) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
 at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
 at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 ... 27 more
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.utils.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Ljava/lang/Object;
 at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
 at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
 ... 27 more

**Comment by SBPrime** [comment]
Please send the server startup log.

**Comment by LemADEC** [comment]
I've got what looks like the same error using AWE 2.2.2


```
[16:56:31 INFO]: [WorldEdit] Loading WorldEdit v6.1.1-SNAPSHOT;3501-c85c9f7
...
[16:56:31 INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v2.2.2
[16:56:31 INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[16:56:31 INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[16:56:31 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[16:56:31 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[16:56:31 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SchematicCommands injected.
[16:56:31 INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.ScriptingCommands injected.
[16:56:31 INFO]: [AsyncWorldEditInjector] Enabled
...
[22:32:38 INFO]: LemADEC issued server command: //help
[22:32:38 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@25c7299e to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
>       at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247) [worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
>       at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2-2016-05-11.jar:git-Spigot-e000104-4cb3258]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.reflect.InvocationTargetException
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
>       at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       ... 19 more
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.utils.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;
[Ljava/lang/String;)Ljava/lang/Object;
>       at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
>       at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-%233501-c85c9f7.jar:?]
>       ... 19 more
```

Is it specific to the non-premium version of AWE ?

**Comment by SBPrime** [comment]
The current version does not support WorldEdit snap builds. Without the full startup log I cant say much more why this error occurs. The premium version works with the stable and snap builds of WE.

**Comment by SBPrime** [comment]
Done.
