### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrTrojan** [SBPrime/AsyncWorldEdit#125]
When writing any error of WorldEdit, it pops up an error in the console:

> Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.utils.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Ljava/lang/Object;
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) ~[WorldEdit.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[WorldEdit.jar:?]
        ... 19 more

**Comment by SBPrime** [comment]
What version of WE are you using.

**Comment by MrTrojan** [comment]
http://dev.bukkit.org/bukkit-plugins/worldedit/files/63-world-edit-6-1-2-up-to-mc-1-9-4/

Moved by 6.1, then everything is fine.

**Comment by SBPrime** [comment]
WE 6.1.2 is currently not supported by the free version of AWE.

**Comment by MrTrojan** [comment]
привет ты чо охуел

2016-05-29 16:49 GMT+06:00, SBPrime <notifications@github.com>:

**Comment by SBPrime** [comment]
@MrTrojan I don't see why did you "thumbed down" my answer. Its only an information why its not working for you. Currently I'm not working on the free version of the plugin for over 6months now. I have clearly stated that. I'm currently working on the premium version, it is updated to the latest version of WorldEdit. The free version might get updated but it might not it all depends if I have time.

**Comment by MrTrojan** [comment]
@SBPrime, вы меня расстроили, что нет поддержки последней версии WorldEdit!

**Comment by SBPrime** [comment]
@MrTrojan All non english comments will be removed.

**Comment by MrTrojan** [comment]
@SBPrime, okey.

**Comment by SBPrime** [comment]
Done.
