### ISSUE TITLE
AWE fails to load on bukkit 1.10.2_R0.1

### ISSUE THREAD

**Issue by HammerHedd** [SBPrime/AsyncWorldEdit#127]
AWE 2.3.0 fails to load with the following errors:

[21:20:35] [Server thread/ERROR]: Could not load 'plugins\AsyncWorldEdit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.primesoft.asyncworldedit.injector.classfactory.IClassFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	... 6 more
[21:20:36] [Server thread/INFO]: [Questioner] Loading Questioner v0.6

Blockshub v 2.0 is also installed.

spigot version gives me:
9:31:23 PM [INFO] This server is running CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

EDIT: This does not occur with the premium version :)

**Comment by SBPrime** [comment]
What version of WorldEdit are you using?

**Comment by HammerHedd** [comment]
/we version gives me

<code>
8:17:04 PM [INFO] WorldEdit version (unknown)

8:17:04 PM [INFO] https://github.com/sk89q/worldedit/

8:17:04 PM [INFO] ----------- Platforms -----------

8:17:04 PM [INFO] * Bukkit-Official (6.1.3;7a097ca)

8:17:04 PM [INFO] ----------- Capabilities -----------

8:17:04 PM [INFO] GAME_HOOKS: Bukkit-Official

8:17:04 PM [INFO] CONFIGURATION: Bukkit-Official

8:17:04 PM [INFO] USER_COMMANDS: Bukkit-Official

8:17:04 PM [INFO] PERMISSIONS: Bukkit-Official

8:17:04 PM [INFO] WORLDEDIT_CUI: Bukkit-Official

8:17:04 PM [INFO] WORLD_EDITING: Bukkit-Official
</code>

**Comment by SBPrime** [comment]
Please update the AWE injector. You are using a mismatched version of AWE and the injector.
