### ISSUE TITLE
BUG - Could not load Plugins.

### ISSUE THREAD

**Issue by Inysal** [SBPrime/AsyncWorldEdit#134]
Hey, here to report this. I don't know what happened. lol

Same message at pastebin: http://pastebin.com/1BXW36Yx

If Pastebin is deleted:

[23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-ActionMessager.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: ActionMessager at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92][23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-WelcomeTitle.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: WelcomeTitle at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92][23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-ActionBarAPI.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: ActionBarAPI at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92][23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-PlotMeCore015.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: PlotMe at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92][23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-BountifulAPI.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: BountifulAPI at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92][23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-PlotMe013g.jar' in folder 'plugins'org.bukkit.plugin.UnknownDependencyException: PlotMe at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] [23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-PlotMeCore016.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: PlotMe at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] [23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-TitleManager.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: TitleManager at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] [23:03:01] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-BarAPI.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: BarAPI at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-850da7e-8e5e90d]

**Comment by TWSSYesterday** [comment]
Versions?
Entire log?
Plugin list?

**Comment by Inysal** [comment]
SBPrime, TWSSYesterday,

I apologize, I was half asleep when I sent this.

Error Log - Formated like Normal.

http://pastebin.com/DDLyE5eS

Versions and Plugin List:

Versions:
  FastCraft+ v0.25
  git-Spigot-850da7e-8e5e90d (MC: 1.10.2)
  1.10.2-R0.1-SNAPSHOT
  Java 1.8.0_92
  AsyncWorldEdit 2.3.2
  AsyncWorldEditInjector 2.3.0
  bChatManager 3.1.5
  BlocksHub 2.0.1
  BottledExp 2.2.2.2
  ChaosSimpleSalvage 1.0.1
  ChatColor2 1.6.8
  ClearLag 2.9.3
  CoreProtect 2.13.1
  CustomEnderChest 1.4.0
  EnchantGUI 1.3.2
  HealthBar 1.8.3
  LagMonitor 1.11.3
  LockettePro 2.4.1
  Orebfuscator4 4.1.4
  PermissionsEx 1.23.4
  ProtocolLib 4.1.0
  RedstoneProximitySensor 2.1.4
  RPGMobMoney 1.5
  SaneEconomy 0.8.4
  SeePlayerInventory 2.1
  SignEdit 3.3.2
  SignShop 2.11.0Dev
  SimpleElevator 1.1.3
  SimpleHomes 2.0.3
  SimpleSort 1.4
  SurvivalFly 1.0
  SwornRPG 3.3
  TeleportSigns 1.1.5
  TreeAssist 5.10.17
  TrophyHeads 1.12.7-46
  UberEnchant 4.0
  Vault 1.5.6-b49
  Vote 1.903
  WelcomeMessages 1.0.2
  WorldEdit 6.1.3;7a097ca
  WorldGuard 6.1.2;e38d98d
===========================================

**Comment by TWSSYesterday** [comment]
Do you have the same issues on the latest Paper Spigot build?
Have you also tried using the latest AsyncWorldEdit on a fresh server?

**Comment by SBPrime** [comment]
Quote from the log:

```
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-ActionMessager.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ActionMessager
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-WelcomeTitle.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WelcomeTitle
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-ActionBarAPI.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ActionBarAPI
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-BountifulAPI.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: BountifulAPI
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-TitleManager.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: TitleManager
[20:08:53] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-BarAPI.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: BarAPI
```

The plugin clearly tells you that you are missing dependency plugins to run AWE progress display plugins.  Your plugin list does not show that you are using any of the required plugins.

In the provided log there are no information’s that would suggest that AWE is not loading.

**Comment by Inysal** [comment]
SBPrime, TWSSYesterday,

I have been gone for the past week, unable to reply to the message. I do have the plugins in the folder. I have:
AsyncWorldEdit
AsyncWorldEdit
AsyncWorldEdit

**Comment by SBPrime** [comment]
1. The plugin is dessigned to work on Bukkit API.
2. For the core plugin to work you need the WorldEdit plugin
3. For progress display plugins you need the "plugin" itself and AWE bridge.
