### ISSUE TITLE
1.12 update ! :D

### ISSUE THREAD

**Issue by TheIntelloBox** [SBPrime/AsyncWorldEdit#136]
Hello ! :D 

Could you add Pre-Release 5: 1.12 support for AsyncWorldEdit when the new version of WorldEdit will be add ? :)

Thanks ! :D 
TheIntelloBox.

**Comment by SBPrime** [comment]
I did not  have time to test this on 1.12. On the other hand I did not have any reports that it does not. Could you be more specific what exactly does not work (log would be nice)?

**Comment by PseudoKnight** [comment]
YamlConfiguration.loadConfiguration(InputStream) was deprecated and has now been removed.

````
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at org.primesoft.asyncworldedit.strings.MessageProvider.loadFile(MessageProvider.java:220) ~[?:?]
````

**Comment by DmitryRendov** [comment]
`[18:24:46] [Server thread/ERROR]: Error occurred while enabling AsyncWorldEdit v2.3.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at org.primesoft.asyncworldedit.strings.MessageProvider.loadFile(MessageProvider.java:220) ~[?:?]
        at org.primesoft.asyncworldedit.strings.MessageProvider.loadDefault(MessageProvider.java:161) ~[?:?]
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.initialiseStrings(AsyncWorldEditBukkit.java:326) ~[?:?]
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onEnable(AsyncWorldEditBukkit.java:172) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-survival-1.12.jar:git-Spigot-ede465d-bb4ae3b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`
