### ISSUE TITLE
Asyncworldedit doesn't work with the latest version of WE

### ISSUE THREAD

**Issue by TheIntelloBox** [SBPrime/AsyncWorldEdit#139]
Hi !

I'm using the latest version of ASyncWorldEdit and WorldEdit, and I'm on Spigot 1.12, but ASyncWorldEdit doesn't work. There's no error,  but I think you should update the plugin.

Please

**Comment by rautamiekka** [comment]
'Latest' ain't a valid version number/string.

**Comment by TheIntelloBox** [comment]
https://dev.bukkit.org/projects/worldedit/files/2431372

**Comment by rautamiekka** [comment]
When the Server is running, `/version` will tell the precise version of Spigot. I think you can open the Server JAR to read it from there, but that's just a guess cuz I don't have to one ATM.

**Comment by SBPrime** [comment]
You need to be more specific. A log would be helpful. 

I tested the master using the latest WE (WorldEdit v6.1.8-SNAPSHOT;3689-b557b2b), everything is ok. The latest release is not compatible with the 1.12. I'll release a new one in this week but my priority is the premium version.

**Comment by KarlTheBee** [comment]
I also got the problem with 1.12 which I thnk you are refering
Spigot build : git-Spigot-cd6ba67-2a2d6d6 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
worldedit version : v6.1.5;4651611
asyncworldedit version : v2.3.2

stack trace : 

```
[15:41:43] [Server thread/ERROR]: Error occurred while enabling AsyncWorldEdit v2.3.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at org.primesoft.asyncworldedit.strings.MessageProvider.loadFile(MessageProvider.java:220) ~[?:?]
	at org.primesoft.asyncworldedit.strings.MessageProvider.loadDefault(MessageProvider.java:161) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.initialiseStrings(AsyncWorldEditBukkit.java:326) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onEnable(AsyncWorldEditBukkit.java:172) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-cd6ba67-2a2d6d6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`
```

**Comment by juliocoliveira** [comment]
Same here, the latest version of this plugin don't work on MC 1.12, and the latest of WE worldedit-bukkit-6.1.8-SNAPSHOT.

Please fix it.

**Comment by SBPrime** [comment]
Did you compile the master or did you use the jar from release?

**Comment by TheIntelloBox** [comment]
JAR from release.

**Comment by SBPrime** [comment]
Well then you guys/gals should read my previous post:

> I tested the **master** (...), everything is ok. The latest **release** is not compatible with the 1.12. I'll release a new one in this week (...)

This means that:
a) You need to compile the master by yourself
b) Wait for the official release.

**Comment by SBPrime** [comment]
New release available.
