### ISSUE TITLE
NoSuchMethodError with spigot 1.12.1

### ISSUE THREAD

**Issue by joblo2213** [SBPrime/AsyncWorldEdit#145]
I tried using AWE on spigot 1.12.1 and except for one NoSuchMethodError which gets frequently thrown everything works fine.

Here is the error log:
```
[14:07:51] [Server thread/WARN]: [AsyncWorldEdit] Task #30 for AsyncWorldEdit v2.3.3 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.TileEntity.a(Lnet/minecraft/server/v1_12_R1/NBTTagCompound;)V
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.readTagIntoTileEntity(Spigot_v1_12_R1.java:116) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.setBlock(Spigot_v1_12_R1.java:253) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:416) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:299) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:290) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.entries.WorldFuncEntryEx.process(WorldFuncEntryEx.java:73) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:351) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:303) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:76) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:213) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-RPG-1.12.1.jar:git-Spigot-65e8124-79e55b6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Server version:** `CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`

**WorldEdit version:** `6.1.7;dd00bb1`

**AsyncWorldEdit version:** `2.3.3`

Thanks for fixing!^^

**Comment by Sjoerrdd** [comment]
Same error...

**Comment by SBPrime** [comment]
The stack trace suggests that this is a bug in WorldEdit. Did you update to the latest available dev build?

**Comment by joblo2213** [comment]
Updated WorldEdit to version `6.1.7.3;cd4729f` (can be found [here](https://dev.bukkit.org/projects/worldedit/files)) and now it is fixed 😄 

I really havn't thought about that it also could be a issue with worldedit, I just read AsyncWorldEdit v2.3.3 generated an exception and then my brain kinda stopped working. 🤦‍♂️ 
So thank you for your support and sorry for wasting your time...

**Comment by SBPrime** [comment]
No problem, your welcome.
