### ISSUE TITLE
org.primesoft.asyncworldedit.injector.classfactory.IClassFactory - NoClassDefFoundError 

### ISSUE THREAD

**Issue by jasoryeh** [SBPrime/AsyncWorldEdit#146]
WorldEdit v.6.1.7.3
AsyncWorldEdit v.2.3.3

Stack trace:
```> [22:54:22 ERROR]: Could not load 'plugins/AsyncWorldEdit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [server.jar:git-PaperMagnet-"584dfbd"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [server.jar:git-PaperMagnet-"584dfbd"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-PaperMagnet-"584dfbd"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-PaperMagnet-"584dfbd"]
... 6 more
Caused by: java.lang.ClassNotFoundException: org.primesoft.asyncworldedit.injector.classfactory.IClassFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperMagnet-"584dfbd"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[server.jar:git-PaperMagnet-"584dfbd"]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-PaperMagnet-"584dfbd"]
... 6 more```

Plugin fails to load, and doesn't even appear in plugins list.

**Comment by SBPrime** [comment]
Did you install the injector plugin?

**Comment by jasoryeh** [comment]
Silly me, didn't see that part of the installation instructions. Thanks.
