### ISSUE TITLE
Generating terrain isn't working!

### ISSUE THREAD

**Issue by BotteledCacti** [SBPrime/AsyncWorldEdit#147]
Hello, I don't seem to be able to do //regen <biome> or /ps generate <biome> as it gives me this error: 

- [23:45:01 WARN]: java.lang.NoSuchMethodError: sun.reflect.ReflectionFactory.newFieldAccessor(Ljava/lang/reflect/Field;Z)Lsun/reflect/FieldAccessor;
[23:45:01 WARN]: 	at com.boydti.fawe.util.ReflectionUtils.setFailsafeFieldValue(ReflectionUtils.java:157)
[23:45:01 WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.regenerateChunk(BukkitQueue_1_12.java:283)
[23:45:01 WARN]: 	at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.regenerateChunk(BukkitQueue_1_12.java:95)
[23:45:01 WARN]: 	at com.boydti.fawe.example.MappedFaweQueue.regenerateChunk(MappedFaweQueue.java:150)
[23:45:01 WARN]: 	at com.sk89q.worldedit.EditSession$12.run(EditSession.java:3550)
[23:45:01 WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:15)
[23:45:01 WARN]: 	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:392)
[23:45:01 WARN]: 	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:388)
[23:45:01 WARN]: 	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:15)
[23:45:01 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[23:45:01 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[23:45:01 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[23:45:01 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[23:45:01 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[23:45:01 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[23:45:01 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)

Thankfull for any help regarding this!

**Comment by SBPrime** [comment]
This error is not caused by my plugin.
