### ISSUE TITLE
ERROR: java.lang.reflect.InvocationTargetExpection: null

### ISSUE THREAD

**Issue by durson54** [SBPrime/AsyncWorldEdit#152]
I get this error when I do //copy command. This shows in console:
`>[2K [21:29:35 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:205) ~[worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.7.3.jar:?]
at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:119) ~[?:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:248) [worldedit-bukkit-6.1.7.3.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247) [worldedit-bukkit-6.1.7.3.jar:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.7.3.jar:?]
at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins%20v1.1.0.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-7228328-e03b1a5]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-7228328-e03b1a5]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-7228328-e03b1a5]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalAccessError: tried to access method com.sk89q.worldedit.EditSession.(Lcom/sk89q/worldedit/util/eventbus/EventBus;Lcom/sk89q/worldedit/world/World;ILcom/sk89q/worldedit/extent/inventory/BlockBag;Lcom/sk89q/worldedit/event/extent/EditSessionEvent;)V from class com.sk89q.worldedit.EditSessionStub
at com.sk89q.worldedit.EditSessionStub.(EditSessionStub.java:59) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.(ThreadSafeEditSession.java:207) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.AsyncEditSession.(AsyncEditSession.java:103) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:127) ~[?:?]
at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:866) ~[?:?]
at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:102) ~[?:?]
... 34 more`

**Comment by SBPrime** [comment]
Please provide the server startup log, WorldEdit version and what command did you try to execute.

**Comment by durson54** [comment]
World Edit version is 6.1.8-SNAPSHOT;cd4729f  and I tried //copy and then //paste if it'd work but it didn't.
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/1606390/latest.log)

**Comment by DuchessNoirNasu** [comment]
Do you know you you got it to work I'm currently having the same issues and I can't seem to figure it out
