### ISSUE TITLE
Unable to store block in undo

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit#181]
```
[19:48:46] [Server thread/INFO]: XXXX issued server command: //replacenear 2 grass sand
[19:48:46] [Thread-29/WARN]: Exception in thread "Thread-29" 
[19:48:46] [Thread-29/WARN]: java.lang.IllegalArgumentException: Can't create a BaseBlock from a fuzzy BlockState!
[19:48:46] [Thread-29/WARN]: 	at com.sk89q.worldedit.world.block.BlockState.toBaseBlock(BlockState.java:211)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.worldedit.blocks.BlockStateHolderWrapper.toBaseBlock(BlockStateHolderWrapper.java:155)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.changesetSerializer.serializers.SerializerBlockChange.serialize(SerializerBlockChange.java:117)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.serialize(SerializerManager.java:501)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:473)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:313)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.save(FileChangeSet.java:210)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSetManager.saveLoop(FileChangeSetManager.java:130)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSetManager.access$000(FileChangeSetManager.java:59)
[19:48:46] [Thread-29/WARN]: 	at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSetManager$1.run(FileChangeSetManager.java:90)
[19:48:46] [Thread-29/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by SBPrime** [comment]
Fixed in beta 5
