### ISSUE TITLE
Server crashes when using voxel sniper fill tool

### ISSUE THREAD

**Issue by Gamerdan1** [SBPrime/AsyncWorldEdit#182]
Whenever i use the command/tool /b e fill for voxel sniper the server stops and then shuts down after a while. (I'm sorry if this is in the wrong place, i'm not sure whether this should be submitted to the VS devs or the Async devs)

**The crash report is attached below;**

[crash-2018-10-28_17.43.12-server.txt](https://github.com/SBPrime/AsyncWorldEdit/files/2526353/crash-2018-10-28_17.43.12-server.txt)

The server console directly after the error is as follows;

```
_[17:19:35 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Writing into PalettedContainer from multiple threads
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException
        at net.minecraft.server.v1_13_R2.DataPaletteBlock.b(SourceFile:43) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DataPaletteBlock.setBlock(SourceFile:110) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.ChunkSection.setType(SourceFile:68) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:488) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:318) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.World.setTypeUpdate(World.java:442) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.BlockDirtSnowSpreadable.a(BlockDirtSnowSpreadable.java:31) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.Block.b(Block.java:364) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.IBlockData.b(SourceFile:265) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:555) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:305) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:956) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        ... 4 more
[17:19:35 ERROR]:       Cause of unexpected exception was
java.lang.IllegalStateException: null
        at net.minecraft.server.v1_13_R2.DataPaletteBlock.b(SourceFile:43) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DataPaletteBlock.setBlock(SourceFile:110) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.ChunkSection.setType(SourceFile:68) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.Chunk.a(Chunk.java:488) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.World.setTypeAndData(World.java:318) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.World.setTypeUpdate(World.java:442) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.BlockDirtSnowSpreadable.a(BlockDirtSnowSpreadable.java:31) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.Block.b(Block.java:364) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.IBlockData.b(SourceFile:265) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:555) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:305) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:956) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[17:19:36 ERROR]: This crash report has been saved to: C:\Users\---\.\crash-reports\crash-2018-10-29_17.19.35-server.txt
[17:19:36 INFO]: Stopping server
[17:19:36 INFO]: [FastAsyncVoxelSniper] Disabling FastAsyncVoxelSniper v18.10.26-94d5028-2069
[17:19:36 INFO]: [WorldEdit] Disabling WorldEdit vunspecified
[17:19:36 INFO]: [Multiverse-Core] Disabling Multiverse-Core v2.5.0-b727
[17:19:36 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v1.0
[17:19:36 INFO]: Saving players_
```

**Comment by SBPrime** [comment]
According to you crash log you are not using AsyncWorldEdit but its clone. Contact the author of that plugin or switch to AsyncWorldEdit. The download can be found here:
https://www.spigotmc.org/resources/asyncworldedit.327/

you can also get the premium version here:
https://www.spigotmc.org/resources/asyncworldedit-premium.9661/reviews#review-245510-79589
