### ISSUE TITLE
AsyncWorldEdit v3.6.0-beta-6 + WorldEdit v7.0.0-SNAPSHOT;3908-dd2fcba  -> NoSuchMethodError

### ISSUE THREAD

**Issue by mart-r** [SBPrime/AsyncWorldEdit#184]
WorldEdit:
`[10:05:16] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.0.0-SNAPSHOT;3908-dd2fcba`

Error while doing //copy:
```
[10:28:49] [Craft Scheduler Thread - 105/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-beta-6 generated an exception while executing task 44916
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushSession()V
   at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:168) ~[?:?]
   at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-413]
   at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-413]
   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-413]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
```

**Comment by SBPrime** [comment]
You are using a not supported version of World edit please update to the supported dev build.

Quote from release notes:
> The version was built against WorldEdit v7.0.0-SNAPSHOT 3919-93de97d and won't work with WorldEdit 6.x and any older builds.
