### ISSUE TITLE
//undo error

### ISSUE THREAD

**Issue by M1904** [SBPrime/AsyncWorldEdit#196]
Hello,

in 3.6.0beta4-Version the undo-command works fine, but in all later versions it doesn't work. today i updated all:
Spigot Version 078a7f5-7fa173e (newest 1.13.2)
Worldedit 7.0.0-beta-04;17f52cb
AWE 3.6.0-rc-03
an //undo also doesn't work

error in log:
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] ***********************************
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] Unable to create undo iterator for ts.167bca3f06e.a87d5343.2
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] ***********************************
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] *
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.io.FileNotFoundException
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * Error message: plugins/AsyncWorldEdit/undo/ec187d28-6d83-4d80-84ef-dd5c1016a575/ts.167bca3f06e.a87d5343.2 (No such file or directory)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * Stack: 
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.open0(Native Method)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.open(RandomAccessFile.java:316)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.changesetSerializer.iterators.BaseFileIterator.initializeStream(BaseFileIterator.java:121)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.changesetSerializer.iterators.UndoFileBackwordIterator.initializeStream(UndoFileBackwordIterator.java:88)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.initializeIterator(FileChangeSet.java:325)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.backwardIterator(FileChangeSet.java:134)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.ThreadSafeChangeSet.backwardIterator(ThreadSafeChangeSet.java:100)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.MemoryMonitorChangeSet.backwardIterator(MemoryMonitorChangeSet.java:171)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doUndo(ThreadSafeEditSession.java:806)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:78)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncEditSession.undo(AsyncEditSession.java:141)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.LocalSession.undo(LocalSession.java:234)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.undo(WrappedLocalSession.java:479)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:63)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.reflect.Method.invoke(Method.java:498)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:211)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.reflect.Method.invoke(Method.java:498)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:231)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[15:49:22] [Server thread/INFO]: [AsyncWorldEdit] ***********************************

Please help me. Thx

P.S. actually also signs cannot copied

**Comment by M1904** [comment]
i changed nothing in the undo-configuration, here the settings:
  undo:
    memoryLowMain: cancel
    memoryLow: wait
    memoryLowStorage: wait
    storeOnDisk: true
    keepSessionOnLogoutFor: 0
    keepUndoFileFor: 0
    undoFileCleanupInterval: 30

is this correct?

there ist no difference between fullblocks, halfslabs oder trapdoors. 

i only //cut 1 block (red concrete). After //undo i get this error:

[18:31:34] [Server thread/INFO]: Minecrafter1904 issued server command: //undo
[18:31:34] [Craft Scheduler Thread - 230/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-03 generated an exception while executing task 307454
java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to com.sk89q.worldedit.bukkit.BukkitWorld
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldEditFlagHandler.setBlock(WorldEditFlagHandler.java:38) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:114) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:94) ~[?:?]
	at com.sk89q.worldedit.function.operation.SetLocatedBlocks.resume(SetLocatedBlocks.java:43) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.__e8d4421252ad42619e19a861339703c9__completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__e8d4421252ad42619e19a861339703c9__completeBlindly.execute(Unknown Source) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:78) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:767) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.flushSession(ThreadSafeEditSession.java:612) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:87) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:155) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

please tell me, you see the problem. :P

**Comment by SBPrime** [comment]
> i changed nothing in the undo-configuration, here the settings:

If its default then its ok. I assume that you did not change anything in WE config regarding undos?

> i only //cut 1 block (red concrete). 

Can you provide log for the cut?

```java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to com.sk89q.worldedit.bukkit.BukkitWorld
at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldEditFlagHandler.setBlock(WorldEditFlagHandler.java:38) ~[?:?]```

You need to update the worldedit flags to dev version. The one that you are using does not support WE beta.

**Comment by M1904** [comment]
which worldedit-flags? did you mean worldguard-flags?
WorldGuard Extra Flags needs:
          WorldGuard 7 #1754 and above
              MC 1.13
              Plugin: Latest
i got the latest 4.1.1

on cut-command is no error:
[18:31:31] [Server thread/INFO]: Minecrafter1904 issued server command: //cut
[18:31:34] [Server thread/INFO]: Minecrafter1904 issued server command: //undo
[18:31:34] [Craft Scheduler Thread - 230/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-03 generated an exception while executing task 307454
java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to com.sk89q.worldedit.bukkit.BukkitWorld

no, i changing nothing in we-config. but rlly, in 3.6.0-beta4 undo works fine but since the latest spigot-update all NBT-Blocks/Entities gave an error

**Comment by M1904** [comment]
wow, i thank you! exactly this was the problem! thx thx thx!
now all works fine, except signs copy.
there is no error in console, it looks like "there ist no sign" for AWE

the same result by toggle awe. WE-Problem?

**Comment by SBPrime** [comment]
Regarding signs, what do you mean there are not working? I tested with the beta-4 and awe-rc-3 on spigot 1.13.2 signs do get copied and paste. Can you share the log for signs?

**Comment by M1904** [comment]
see it here: http://sendvid.com/7lsrzhzt

there is no error in console:
[11:02:49] [Server thread/INFO]: Minecrafter1904 issued server command: //copy
[11:02:52] [Server thread/INFO]: Minecrafter1904 issued server command: //paste
[11:06:40] [Server thread/INFO]: [0;30;1m[[0;35;22m[21mInformation[m[0;30;1m] [0;37;22mIch bin 

i have no idea

**Comment by SBPrime** [comment]
I have no idea what might be the cause. I can suggest 3 things:
1 try doing AWE toggle and then copy pastę the sign
2 try the copy paste without AWE installed
3 if neither works try a berebone server and add plugin one by one atarting with AWE + we.

**Comment by M1904** [comment]
point 1 i tested, at toggle awe the same result.
the other 2 points i try next week :) thanks a lot for the undo-problem. i thought, i had the latest version of worldguard extra flags, but i didn't. thanks a lot for your help :)
