### ISSUE TITLE
IllegalArgumentException when doing //replace lime_wool yellow_wool

### ISSUE THREAD

**Issue by mart-r** [SBPrime/AsyncWorldEdit#201]
29.12 14:12:47 [Server] INFO [PlugMan] Plugin Information: WorldEdit
29.12 14:12:47 [Server] INFO - Version: 7.0.0-SNAPSHOT;3987-f4ed48b
30.12 01:58:49 [Server] INFO [PlugMan] Plugin Information: AsyncWorldEdit
30.12 01:58:49 [Server] INFO - Version: 3.6.0-beta-9

```
[14:06:17] [Server thread/INFO]: Molyticus issued server command: //replace lime_wool yellow_wool
[14:06:17] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[?:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:210) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:218) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1799) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: Can't create a BaseBlock from a fuzzy BlockState!
	at com.sk89q.worldedit.world.block.BlockState.toBaseBlock(BlockState.java:211) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:326) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:89) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:54) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:97) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:74) ~[?:?]
	at com.sk89q.worldedit.extension.factory.BlockFactory.parseFromListInput(BlockFactory.java:65) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromListInput(ExtendedBlockFactory.java:131) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.mask.BlocksMaskParser.parseFromInput(BlocksMaskParser.java:51) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.mask.BlocksMaskParser.parseFromInput(BlocksMaskParser.java:38) ~[?:?]
	at com.sk89q.worldedit.extension.factory.MaskFactory.parseFromInput(MaskFactory.java:85) ~[?:?]
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getMask(WorldEditBinding.java:245) ~[?:?]
	... 33 more
	Suppressed: java.lang.IllegalArgumentException: Can't create a BaseBlock from a fuzzy BlockState!
		at com.sk89q.worldedit.world.block.BlockState.toBaseBlock(BlockState.java:211) ~[?:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:326) ~[?:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:81) ~[?:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:54) ~[?:?]
		at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:69) ~[?:?]
		at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:97) ~[?:?]
		at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:74) ~[?:?]
		at com.sk89q.worldedit.extension.factory.BlockFactory.parseFromListInput(BlockFactory.java:65) ~[?:?]
		at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromListInput(ExtendedBlockFactory.java:131) ~[?:?]
		at com.sk89q.worldedit.extension.factory.parser.mask.BlocksMaskParser.parseFromInput(BlocksMaskParser.java:51) ~[?:?]
		at com.sk89q.worldedit.extension.factory.parser.mask.BlocksMaskParser.parseFromInput(BlocksMaskParser.java:38) ~[?:?]
		at com.sk89q.worldedit.extension.factory.MaskFactory.parseFromInput(MaskFactory.java:85) ~[?:?]
		at com.sk89q.worldedit.internal.command.WorldEditBinding.getMask(WorldEditBinding.java:245) ~[?:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
		at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[?:?]
		at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220) ~[?:?]
		at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[?:?]
		at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:210) ~[?:?]
		at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275) ~[?:?]
		at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[?:?]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
		at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[?:?]
		at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:218) ~[?:?]
		at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) ~[?:?]
		at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-474]
		at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1799) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
		at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
		at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by SBPrime** [comment]
Update AWE to latest version and get back to me.

**Comment by SBPrime** [comment]
No response, closing.
