### ISSUE TITLE
//copy doesn't work

### ISSUE THREAD

**Issue by HookDonn** [SBPrime/AsyncWorldEdit#202]
```
[13:33:02 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:333) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:284) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:951) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 13 more
[13:33:13 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:333) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:284) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:951) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 13 more
[13:33:18 INFO]: HookDonn_ issued server command: //pos2
[13:33:20 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:333) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:284) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:951) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 13 more
[13:33:27 INFO]: HookDonn_ issued server command: //Copy
[13:33:28 WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-03 generated an exception while executing task 170
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
    at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:403) ~[?:?]
    at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:391) ~[?:?]
    at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.getBlock(Spigot_v1_13_R2.java:237) ~[?:?]
    at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:445) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.lambda$getFullBlock$20(AsyncWorld.java:710) ~[?:?]
    at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:641) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getFullBlock(AsyncWorld.java:709) ~[?:?]
    at com.sk89q.worldedit.EditSession.getFullBlock(EditSession.java:482) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doGetFullBlock(ThreadSafeEditSession.java:769) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.lambda$getFullBlock$2(ThreadSafeEditSession.java:513) ~[?:?]
    at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:651) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.getFullBlock(ThreadSafeEditSession.java:513) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.getFullBlock(CancelabeEditSession.java:271) ~[?:?]
    at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:72) ~[?:?]
    at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
    at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57) ~[?:?]
    at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
    at com.sk89q.worldedit.function.operation.Operations.__6877f4b38b73455185f69ecf953d7e01__completeLegacy(Operations.java:55) ~[?:?]
    at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__6877f4b38b73455185f69ecf953d7e01__completeLegacy.execute(Unknown Source) ~[?:?]
    at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor$1.task(AsyncOperationProcessor.java:163) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[13:33:35 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:232) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.save(WorldServer.java:863) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.save(CraftWorld.java:874) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:855) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 11 more
[13:33:36 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:333) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:284) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:951) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 13 more
```

AsyncWorldEdit - Premium 3.6.0-rc-03
worldedit-bukkit-7.0.0-beta-03.jar
worldguard-legacy-7.0.0-beta-02.jar
Spigot : git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by HookDonn** [comment]
Fail, it's AsyncWorldEdit - Premium.
