### ISSUE TITLE
Error when pasting

### ISSUE THREAD

**Issue by TheRootAdmin** [SBPrime/AsyncWorldEdit#210]
WE Ver: WorldEdit v7.0.0-beta-04
AWE Ver: Premium 3.6.0-rc-04b

issued server command: //paste
[11:47:53 WARN]: Exception in thread "Thread-17"
[11:47:53 WARN]: java.lang.NoSuchMethodError: com.sk89q.worldedit.history.change.BlockChange.getCurrent()Lcom/sk89q/worldedit/world/block/BlockStateHolder;
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.changesetSerializer.serializers.SerializerBlockChange.serialize(SerializerBlockChange.java:98)
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.serialize(SerializerManager.java:502)
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:473)
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.save(SerializerManager.java:313)
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.save(FileChangeSet.java:210)
[11:47:53 WARN]:        at org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSetManager.saveLoop(FileChangeSetManager.java:126)
[11:47:53 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by SBPrime** [comment]
Duplicate for: SBPrime/AsyncWorldEdit-Premium/issues/152
