### ISSUE TITLE
UPDATE 1.14.1 PLEASE

### ISSUE THREAD

**Issue by successed** [SBPrime/AsyncWorldEdit#228]
[18:42:42] [Server thread/INFO]: [AsyncWorldEdit] Injector platform set to: InjectorBukkit
[18:42:42] [Server thread/INFO]: [AsyncWorldEdit] Injecting WorldEdit classes...
[18:42:42] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector2
[18:42:42] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector3
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector2
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector3
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockStateHolder
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BaseBlock
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockState
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.entity.BaseEntity
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.Location
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.biome.BaseBiome
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] *
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.io.IOException
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Class not found
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * Stack: 
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.readStream(ClassReader.java:261)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.<init>(ClassReader.java:234)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.ClassInjectorBukkit.getClassReader(ClassInjectorBukkit.java:121)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:248)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:180)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:237)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName(Class.java:348)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:216)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] Unable to initialize injector.
[18:42:43] [Server thread/INFO]: [AsyncWorldEdit] ERROR: Unable to enable the injector.

**Comment by successed** [comment]
[19:40:34] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.6.0-rc-05
[19:40:34] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] null initializing AsyncWorldEdit v3.6.0-rc-05 (Is it up to date?)
java.lang.NullPointerException: null
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:283) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:357) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by SBPrime** [comment]
You are using mismatched versions of WE and AWE. Please check release notes for compatibility.

**Comment by successed** [comment]
this worldedit 1.14.1

**Comment by SBPrime** [comment]
AsyncWorldEdit v3.6.0-rc-05 is compatible with WorldEdit up to 7.0.0-beta5. Please read release notes.
