### ISSUE TITLE
Async Premium Error 1.14.3

### ISSUE THREAD

**Issue by actus18** [SBPrime/AsyncWorldEdit#245]
```
[16:37:06] [Server thread/ERROR]: null initializing AsyncWorldEdit v3.6.9 (Is it up to date?)
java.lang.NullPointerException: null
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:288) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

I use the Serverversion spigot-1.14.3

**Comment by SBPrime** [comment]
Send me the full server startup log.

**Comment by actus18** [comment]
Fixed but how can i set very Fast Schematic? In the video i have see /chunk paste but this dont work.

**Comment by SBPrime** [comment]
Because of compatibility and stability issues this was disabled.
