### ISSUE TITLE
Brushes arent working as they used to

### ISSUE THREAD

**Issue by Legendbender** [SBPrime/AsyncWorldEdit#250]
Caused by: java.lang.ClassCastException: java.lang.Class incompatible with java.lang.Class$CacheKey
at java.lang.Class$CacheKey.equals(Class.java:3441) ~[?:1.8.0_212]
at java.util.HashMap.getNode(HashMap.java:572) ~[?:1.8.0_212]
at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_212]
at java.util.HashSet.contains(HashSet.java:204) ~[?:1.8.0_212]
at org.primesoft.asyncworldedit.injector.scanner.ClassScanner.scan(ClassScanner.java:168) ~[?:?]
at org.primesoft.asyncworldedit.injector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:129) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:62) ~[?:?]
at com.sk89q.worldedit.command.tool.brush.OperationFactoryBrush.build(OperationFactoryBrush.java:49) ~[?:?]
at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:192) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.command.tool.WrappedBrushTool.actPrimary(WrappedBrushTool.java:169) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:454) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
... 25 more

Worldedit & WG are the latest version for <1.13 versions
Server Version is 1.12.2

**Comment by SBPrime** [comment]
Please send the exact version of WE and AWE.

**Comment by Legendbender** [comment]
AWE 3.5.4 / WE 6.1.9

**Comment by Legendbender** [comment]
I am not sure if that has something to with also schematic copy but when i try to use it, server crashes giving that log https://file.properties/paste/wiqocesove.sql

**Comment by Legendbender** [comment]
And while using AWE API, that occurs https://file.properties/paste/goxarigili.md and blocks are replace 1 by 1 for 2.7M blocks lol, is there a configuration to set it?

**Comment by SBPrime** [comment]
The 1'st error: there is no mention of AWE in the stack trace. It looks like AWE did not kick in.
2'nd error: I would need to see the implementation of the API call.

What did you change before the error started to occur? Please send the full server startup log.

Also U would suggest trying out AWE 3.6.9 and WorldEdit 6.1.7.3

**Comment by Legendbender** [comment]
My server version is 1.12.2 sadly, it's been fixed, it had a problem with PlotSquared but now the only problem is that, it pastes the blocks 1 by 1 and sends that log "https://hastebin.com/mucorokeda.md" is there any part that involving AWE?

**Comment by SBPrime** [comment]
Is this Paper?

**Comment by SBPrime** [comment]
Paper has issues with chunk load/unload events. It was rewritten in 1.13+ I don't think that I can help you with that part.

**Comment by Legendbender** [comment]
Sad, wish you had provided it for those who are not using 1.13+ versions.

**Comment by SBPrime** [comment]
The problem is that it was not fixable in 1.12 paper. It was fixed in 1.13 because of API changes.

**Comment by Legendbender** [comment]
i used that on my other server it worked well idk
