### ISSUE TITLE
The plugin does not work on WE7.1 dev build

### ISSUE THREAD

**Issue by bloodyearth** [SBPrime/AsyncWorldEdit#256]
Full server log: [latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/3613045/latest.log)

Paper Spigot 1.14.4, build 187.
World Edit 7.1.0
AsyncWorldEdit 3.6.10

**Comment by FlashLight34** [comment]
`[21:55:00 INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.6.10
[21:55:00 ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] null initializing AsyncWorldEdit v3.6.10 (Is it up to date?)
java.lang.NullPointerException: null
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:288) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:857) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1135) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-186]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[21:55:00 INFO]: [WorldEditSUI] Loading WorldEditSUI v1.6.1`

**Comment by SBPrime** [comment]
@bloodyearth snapshots are not supported. Please use the supported version of the plugin.
@FlashLight34 this is not the full startup log.

**Comment by FlashLight34** [comment]
ok but you can check at line AsyncWorldEditBukkit.java:288 a null exception :D

**Comment by bloodyearth** [comment]
@SBPrime where i can get supported version of the plugin? I try some versions and it stil not working.

**Comment by SBPrime** [comment]
Only official releases of worldedit found here are supported https://dev.bukkit.org/projects/worldedit
Dev builds might work might not.

**Comment by bloodyearth** [comment]
Thx

**Comment by Tsoccerguy3** [comment]
SBPrime , maybe he is asking that you start support for the 7.1 branch here https://builds.enginehub.org/job/worldedit?branch=master . Switch from 7.01 to 7.1

**Comment by valenvaio** [comment]
Switch from 7.01 to 7.1

**Comment by SBPrime** [comment]
Support added in 3.6.15-BETA-01
