### ISSUE TITLE
PaperMC

### ISSUE THREAD

**Issue by Mitsu13Ion** [SBPrime/AsyncWorldEdit#262]
Hello, I use paper 1.13.2 and awe don't want to load

[12:48:29 INFO]: [AsyncWorldEdit] Injector platform set to: InjectorBukkit
[12:48:29 INFO]: [AsyncWorldEdit] Injecting NMS classes...
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class net.minecraft.server.v1_13_R2.ChunkProviderServer
[12:48:29 INFO]: [AsyncWorldEdit] Injecting WorldEdit classes...
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.eventbus.EventBus
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector2
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector3
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector2
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector3
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockStateHolder
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BaseBlock
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockState
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.entity.BaseEntity
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.Location
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.biome.BiomeType
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.weather.WeatherType
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.EditSession
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.function.operation.Operations
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extension.platform.PlayerProxy
[12:48:29 INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.collection.LocatedBlockList
[12:48:29 INFO]: [AsyncWorldEdit] ****************************
[12:48:29 INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[12:48:29 INFO]: [AsyncWorldEdit] ****************************
[12:48:29 INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[12:48:29 INFO]: [AsyncWorldEdit] *
[12:48:29 INFO]: [AsyncWorldEdit] * Exception: java.lang.IllegalStateException
[12:48:29 INFO]: [AsyncWorldEdit] * Error message: get not found
[12:48:29 INFO]: [AsyncWorldEdit] * Stack:
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.utils.SimpleValidator.validate(SimpleValidator.java:70)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.util.collection.LocatedBlockListVisitor.validate(LocatedBlockListVisitor.java:106)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:316)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:283)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:204)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:175)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:239)
[12:48:29 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
[12:48:29 INFO]: [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
[12:48:29 INFO]: [AsyncWorldEdit] * java.lang.Class.forName(Class.java:348)
[12:48:29 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[12:48:29 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[12:48:29 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[12:48:29 INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[12:48:29 INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331)
[12:48:29 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235)
[12:48:29 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[12:48:29 INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[12:48:29 INFO]: [AsyncWorldEdit] ****************************
[12:48:29 INFO]: [AsyncWorldEdit] Unable to initialize injector.
[12:48:29 INFO]: [AsyncWorldEdit] ERROR: Unable to enable the injector.

[12:48:32 ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] null initializing AsyncWorldEdit v3.6.10 (Is it up to date?)
java.lang.NullPointerException: null
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:288) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336) ~[patched_1.13.2.jar:git-Paper-650]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-650]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-650]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by SBPrime** [comment]
Update to AWE 3.6.11.

**Comment by Mitsu13Ion** [comment]
I'm not premium
