### ISSUE TITLE
Errors on load in both worldedit 7.0 and worldedit 7.1.0

### ISSUE THREAD

**Issue by mrcoffee1026** [SBPrime/AsyncWorldEdit#266]
In 7.0:
```
[21:00:12] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_14_R2 as the Bukkit adapter
[21:00:12] [Server thread/WARN]: Failed to load the built-in legacy id registry
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.IBlockState.d()Ljava/util/Collection;
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_14_R2.getProperties(Spigot_v1_14_R2.java:398) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitBlockRegistry.getProperties(BukkitBlockRegistry.java:52) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockType.lambda$getPropertyMap$1(BlockType.java:121) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockType.updateField(BlockType.java:74) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockType.getPropertyMap(BlockType.java:120) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseProperties(DefaultBlockParser.java:171) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:314) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:88) ~[?:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:61) ~[?:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:73) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:98) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:75) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.loadFromResource(LegacyMapper.java:99) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.<init>(LegacyMapper.java:66) ~[?:?]
	at com.sk89q.worldedit.world.registry.LegacyMapper.getInstance(LegacyMapper.java:179) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.loadMappings(WorldEdit.java:367) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:153) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$100(WorldEditPlugin.java:89) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:466) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-225]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:445) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[21:00:12] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface

```

In 7.1.0:
```
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Injector platform set to: InjectorBukkit
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Injecting NMS classes...
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Injecting WorldEdit classes...
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.eventbus.EventBus
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector2
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector3
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector2
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector3
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockStateHolder
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BaseBlock
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockState
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.entity.BaseEntity
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.Location
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.biome.BiomeType
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.weather.WeatherType
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.EditSession
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.function.operation.Operations
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extension.platform.PlayerProxy
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.collection.LocatedBlockList
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extent.reorder.MultiStageReorder
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.extent.reorder.ChunkBatchingExtent
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.AbstractRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.EllipsoidRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.ConvexPolyhedralRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.TransformRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.RegionIntersection
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.NullRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.Polygonal2DRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.CylinderRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.regions.CuboidRegion
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.command.SnapshotUtilCommands
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] *
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.lang.IllegalStateException
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Missing method 'restore(Lcom/sk89q/worldedit/entity/Player;Lcom/sk89q/worldedit/LocalSession;Lcom/sk89q/worldedit/EditSession;Ljava/lang/String;)V'
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * Stack: 
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.utils.SimpleValidator.validate(SimpleValidator.java:70)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.util.stream.ReferencePipeline.forEach(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.worldedit.command.BaseCommandsVisitor.validate(BaseCommandsVisitor.java:146)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:334)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:296)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:220)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:175)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:239)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Unknown Source)
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] Unable to initialize injector.
[21:07:09] [Server thread/INFO]: [AsyncWorldEdit] ERROR: Unable to enable the injector.

```
and
```
[21:07:12] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.6.13
[21:07:12] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] null initializing AsyncWorldEdit v3.6.13 (Is it up to date?)
java.lang.NullPointerException: null
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:288) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

```

This is on 3.6.13 and paper-225

**Comment by mrcoffee1026** [comment]
oh seems ok with w/e 7.0.1 which i thought was the second one i was trying... that must have been off of recent builds.  Anyway for now I should be able to use that as a workaround but if they still have the same changes in the later builds the 7.1.0 will need dealt with eventually... I guess the 7.0.0 issue goes away though.

**Comment by SBPrime** [comment]
7.1.0 support will be added whe its officially released on dev bukkit. There is an issue for updating.

Closing: duplocate of https://github.com/SBPrime/AsyncWorldEdit/issues/256
