### ISSUE TITLE
WorldEdit not working since Premium V. 3.6.13

### ISSUE THREAD

**Issue by fichdlmaa** [SBPrime/AsyncWorldEdit#268]
Hello *, 
**all works fine including Version 3.6.12 on latest SpigotMC.**

With 3.6.13 I got Java error in server console when trying //wand 
There is no error in player chat. There, *nothing* happens (no axe).
Using (manually given) wand is like no WE is installed ...

Same problem in latest 3.6.14. See server messages below.

I will return to 3.6.12 until there is a solution ;-)
(NO permissions problem! Frrangge is server admin)

Greets

FichdlMaa

Server Messages:
...
[15:45:52] [Server thread/INFO]: Frrangge issued server command: //wand
[15:45:52] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@4151e86c to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:341) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 23 more
Caused by: java.lang.NullPointerException
	at org.primesoft.asyncworldedit.playerManager.PlayerManager.findPlayer(PlayerManager.java:310) ~[?:?]
	at org.primesoft.asyncworldedit.playerManager.PlayerManager.getPlayer(PlayerManager.java:249) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.getPlayer(AsyncSessionManager.java:243) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.getIfPresent(AsyncSessionManager.java:102) ~[?:?]
	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:151) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.get(AsyncSessionManager.java:113) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:451) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 23 more
...

--

**Comment by SBPrime** [comment]
Check your config, it most likely has 0b and update to 3.6.14. Version 3.6.12 ignores the config (bug), 3.6.13 is not able to update some configs to latest version required by AWE that causes the config to be reset to 0b.

**Comment by fichdlmaa** [comment]
Hello SBPrime. 
I first wondered what You mean with 0b - okay 0 B(yte) :-)

**You've right! config.yml with 0 B.** (Why this???) 
I simply deleted it, swapped old 3.6.12 with new 3.6.14 and restarted *) 
the server.   Now it works!   

**Thank You very much -- and for you very good work, too.**


--
*) Perhaps reload would have been enough, but for being sure).

**Comment by SBPrime** [comment]
There was a bug in 3.6.13 that caused AWE to badly update the config. The bug was fixed in 3.6.14.
