### ISSUE TITLE
Regen

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#275]
I try to regenerate chunks but AWE doesn't seem to like it.
```
[12:58:20 INFO]: Player123ABC issued server command: //regen
[12:58:25 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:58:25 WARN]: Regeneration via adapter failed.
java.lang.NullPointerException: The world was unloaded and the reference is unavailable
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.14.4.jar:git-Paper-235]
at com.sk89q.worldedit.bukkit.BukkitWorld.getWorld(BukkitWorld.java:142) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:443) ~[?:?]
at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_14_R4.regenerate(Spigot_v1_14_R4.java:605) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:183) ~[?:?]
at com.sk89q.worldedit.command.RegionCommands.regenerateChunk(RegionCommands.java:415) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:568) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:347) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
Without AWE it works so I thought to exclude the `//regen` command from AWE with:
```
  disabledOperations:
    - regenerate
    - regen
    - regeneratechunk
```
but so far, I haven't figured out what works

AsyncWorldEdit v3.6.15-BETA-01
WorldEdit v7.1.0-SNAPSHOT;4787-aeb8935

**Comment by SBPrime** [comment]
I'm unable to reproduce using a bare-bone server. It might be caused by different plugins conflicting. Please enable debug mode in AWE, do the command again and send me the logs.

**Comment by x1p** [comment]
https://hastebin.com/gipicusuja.md

**Comment by SBPrime** [comment]
It makes sensie, but does not help at all.
I would suggest trying to reproduce on a barebone server and then add plugins. What version of the server are you using? Could you try we 7.1.0 beta and the latest release?

**Comment by x1p** [comment]
Again,
As bare as can be; fresh world, plugins:
`[Plugins (4): AsyncWorldEdit, LuckPerms, WorldEdit, WorldGuard`
Versions: AWE 3.6.15 LP 4.4.31, WE 7.0.0-beta-1, WG 7.0.1
I noticed that sptigot.yml has this added:
```
world-settings:
  worldeditregentempworld:
    verbose: false
```

**Comment by SBPrime** [comment]
Did you try without WG?

**Comment by x1p** [comment]
Only WE (and no WG) it works fine
With AWE it doesn't work

**Comment by SBPrime** [comment]
Ok then it might be paper (I'm testing everything on regular spigot :P ), thanks for testing.

**Comment by SBPrime** [comment]
Still no luck. On a clean paper server (WE + AWE) it works without any problems.

**Comment by x1p** [comment]
It works with WorldEdit v7.1.0-SNAPSHOT;4799-79c11c5
