### ISSUE TITLE
An unexpected error while handling a WorldEdit command

### ISSUE THREAD

**Issue by ShabbirSheeps** [SBPrime/AsyncWorldEdit#283]
I tried doing **//set grass** and this error occurred
I am using the latest version of AsyncWorldEdit which right now is 3.6.16. We are running on "**Paper version git-Paper-49 (MC: 1.15.1)**"

Error 
`>.... [23:29:00 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ClassCastException: java.lang.Integer cannot be cast to com.sk89q.worldedit.math.BlockVector3
at com.sk89q.worldedit.util.collection.BlockMap.get(BlockMap.java:342) ~[?:?]
at com.sk89q.worldedit.util.collection.BlockMap.get(BlockMap.java:50) ~[?:?]
at java.util.concurrent.ConcurrentHashMap.equals(ConcurrentHashMap.java:1350) ~[?:1.8.0_212]
at java.util.HashMap.getNode(HashMap.java:572) ~[?:1.8.0_212]
at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_212]
at java.util.HashSet.contains(HashSet.java:204) ~[?:1.8.0_212]
at org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.scan(ClassScanner.java:178) ~[?:?]
at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:188) ~[?:?]
at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:90) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:808) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.flushSession(ThreadSafeEditSession.java:637) ~[?:?]
at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:319) ~[?:?]
at com.sk89q.worldedit.LocalSession.prepareEditingExtents(LocalSession.java:995) ~[?:?]
at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:988) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.createEditSession(WrappedLocalSession.java:161) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:243) ~[?:?]
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_212]
at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212]
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_212]
at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:639) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:400) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:347) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.1.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1096) ~[patched_1.15.1.jar:git-Paper-49]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by SBPrime** [comment]
Please provide spigot user name. This log looks like a problem with third party plugin. Set log level to debug and send log for simple set.

**Comment by ShabbirSheeps** [comment]
**Spigot Username:** Shabbir_Sheeps
**Additional Information:** As you told me to do, I set the log level to debug in config.yml. After doing that I saved the file and i restarted the server. When the server was back on, I selected an area and then I did //set air. The plugin AsyncWorldEdit stopped the server (probably killed it) and started spamming the console with errors.
**Plugin Spigot Link:** https://www.spigotmc.org/resources/asyncworldedit.327/
**Where I downloaded it from:** https://github.com/SBPrime/AsyncWorldEdit/releases/tag/v3.6.16

Here is the latest.log file:
[latest.LOG](https://github.com/SBPrime/AsyncWorldEdit/files/4085182/latest.LOG)

**Comment by SBPrime** [comment]
The error is caused by lands. You did not configure AWE properly to work with lands. This is not a bug of AWE, full support on how to setup the server is available for premium users.
