### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by Steev93** [SBPrime/AsyncWorldEdit#303]
Hey,

As seen with my issue here;
https://github.com/EngineHub/WorldEdit/issues/1299

ASync is blocking me from completing commands via console to run.

Can you allow bypass in the console in the premium version?

**Comment by Steev93** [comment]
Didn't even see the section in config to ignore this.

Sorted

**Comment by Steev93** [comment]
`>....       [07:36:02]: Set the world override to admin. (Use //world to go back to default)
>....       [07:36:02]: You need to provide a world (Try //world)
>....       [07:36:02]: You need to provide a world (Try //world)
>....       [07:36:02]: Please report this error: [See console]
>....       [07:36:02]: java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
>....      [07:36:02 ERROR: An unexpected error while handling a WorldEdit command ]
java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
    at com.sk89q.worldedit.EditSession.setBatchingChunks(EditSession.java:532) ~[?:?]
    at com.sk89q.worldedit.EditSession.enableStandardMode(EditSession.java:303) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
    at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
    at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
    at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
    at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
    at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
    at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:639) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:400) ~[?:?]
    at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-171]
    at it.mri.mycommand.Main.RunCommandsAsConsoleSender(Main.java:644) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.Execute(BlockListener.java:134) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.onPlayerInteract(BlockListener.java:101) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor184.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-171]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1021) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:944) ~[patched_1.15.2.jar:git-Paper-171]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>....       [07:36:13]: Grim801 issued server command: /home storage
>....       [07:36:21]: Grim801 issued server command: /back
>....       [07:36:29]: [ShopGUIPlus] MynKrafter123 bought 1 x Elytra for 10,000$ from itemofmonth shop
>....       [07:36:30]: MynKrafter123 has reached the goal [Sky's the Limit]
>....       [07:36:34]: kitcatswirl issued server command: /job
>....       [07:36:34]: [Mycmd] The /command of edit returned null. Fix it.
>....       [07:36:34]: kitcatswirl issued mycmd command ID(43) /job
>....       [07:36:34]: kitcatswirl issued server command: /warp job
>....       [07:36:36]: MynKrafter123 issued server command: /home
>....       [07:36:39]: Steev_93 issued server command: /awe reload
>....       [07:36:40]: HeadDB> given MynKrafter123 a random head
>....       [07:36:42]: Steev_93 issued server command: /awe reload all
>....       [07:36:42]: [AsyncWorldEdit] Steev_93 reloading config (all)...
>....       [07:36:43]: Set the world override to admin. (Use //world to go back to default)
>....       [07:36:43]: You need to provide a world (Try //world)
>....       [07:36:43]: You need to provide a world (Try //world)
>....       [07:36:43]: Please report this error: [See console]
>....       [07:36:43]: java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
>....      [07:36:43 ERROR: An unexpected error while handling a WorldEdit command ]
java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
    at com.sk89q.worldedit.EditSession.setBatchingChunks(EditSession.java:532) ~[?:?]
    at com.sk89q.worldedit.EditSession.enableStandardMode(EditSession.java:303) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
    at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
    at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
    at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
    at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
    at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
    at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:639) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:400) ~[?:?]
    at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-171]
    at it.mri.mycommand.Main.RunCommandsAsConsoleSender(Main.java:644) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.Execute(BlockListener.java:134) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.onPlayerInteract(BlockListener.java:101) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor184.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-171]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1021) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:944) ~[patched_1.15.2.jar:git-Paper-171]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
`

**Comment by SBPrime** [comment]
My plugin does not do anything to the console therefore I don't understand what do need.
In addition I don't see AWE in the stack trace therefore please reproduce it without AWE. If it does not work then report the problem to WE, if it works then get back to me.

**Comment by Steev93** [comment]
> My plugin does not do anything to the console therefore I don't understand what do need.
> In addition I don't see AWE in the stack trace therefore please reproduce it without AWE. If it does not work then report the problem to WE, if it works then get back to me.

Please see this, doesn't work with async enabled, I disable this and it works
https://screencast-o-matic.com/watch/cYfoiqzQsY

**Comment by Steev93** [comment]
~ bump

**Comment by SBPrime** [comment]
Without access to the plugin that you are using I won't be able to help:
```at it.mri.mycommand.Main.RunCommandsAsConsoleSender(Main.java:644) ~[?:?]```

**Comment by Steev93** [comment]
https://www.spigotmc.org/resources/mycommand.22272/

**Comment by SBPrime** [comment]
@Steev93 Sorry for getting back to you so late. The plugin works without any issues for this test set of commands:
```
we_test:
  command: /sb
  type: RUN_COMMAND
  runcmd:
  - '/awe speed 1'
  - '//pos1 72,63,-155'
  - '//pos2 69,63,-152'
  - '//set glass,glowstone,air,bedrock,obsidian'
```

If its not working for you you would need to provide more details, what is the command that you are executing, how its setup, and how you are executing it.

**Comment by Steev93** [comment]
I get this GIANT error

`[05:49:09 INFO]: Please report this error: [See console]
[05:49:09 INFO]: java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
[05:49:09 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
at com.sk89q.worldedit.EditSession.setBatchingChunks(EditSession.java:532) ~[?:?]
at com.sk89q.worldedit.EditSession.enableStandardMode(EditSession.java:303) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:639) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:400) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:107) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:71) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:496) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-214]
at it.mri.mycommand.Main.RunCommandsAsConsoleSender(Main.java:644) ~[?:?]
at it.mri.mycommand.listener.BlockListener.Execute(BlockListener.java:134) ~[?:?]
at it.mri.mycommand.listener.BlockListener.onPlayerInteract(BlockListener.java:101) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor180.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-214]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-214]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1076) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1069) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.15.2.jar:git-Paper-214]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by Steev93** [comment]
I'll mae a recording later on about it all

**Comment by SBPrime** [comment]
I’m not saying that there is no problem, I’m saying that I need your config for the console commands to test the plugin. As you can see a simple set of commands work without any issues.
