### ISSUE TITLE
AWE 3.7.2 Does not run 

### ISSUE THREAD

**Issue by jan5326** [SBPrime/AsyncWorldEdit#318]
My server is running on CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Yes i know it's old and unsupported) and I'm using worldedit version 6.1.9. The following error message is below

```
15:34:26] [Server thread/ERROR]: Could not load 'plugins\AsyncWorldEdit-3.7.2 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.IllegalStateException: Unable to get loaders.
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:115) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:113) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
```

Does this mean that my server's version is unsupported? Is there anyway this can be fixed?

Thank you

**Comment by SBPrime** [comment]
Provide full server startup log.

**Comment by jan5326** [comment]
`[10:14:08] [Server thread/INFO]: Starting minecraft server version 1.8.8
[10:14:08] [Server thread/INFO]: Loading properties
[10:14:08] [Server thread/INFO]: Default game type: SURVIVAL
[10:14:08] [Server thread/INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[10:14:08] [Server thread/INFO]: Debug logging is disabled
[10:14:08] [Server thread/INFO]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[10:14:08] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:14:08] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:14:08] [Server thread/INFO]: Data value allowed items: 
[10:14:08] [Server thread/INFO]: Generating keypair
[10:14:08] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:14:08] [Server thread/INFO]: Using default channel type
[10:14:09] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[10:14:09] [Server thread/ERROR]: Could not load 'plugins\AsyncWorldEdit-3.7.2 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.IllegalStateException: Unable to get loaders.
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:115) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:113) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
[10:14:09] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
[10:14:09] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[10:14:09] [Server thread/INFO]: Preparing level "Spawn"
[10:14:09] [Server thread/INFO]: -------- World Settings For [Spawn] --------
[10:14:09] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:14:09] [Server thread/INFO]: Item Despawn Rate: 6000
[10:14:09] [Server thread/INFO]: Item Merge Radius: 2.5
[10:14:09] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:14:09] [Server thread/INFO]: View Distance: 10
[10:14:09] [Server thread/INFO]: Chunks to Grow per Tick: 650
[10:14:09] [Server thread/INFO]: Clear tick list: false
[10:14:09] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:14:09] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:14:09] [Server thread/INFO]: Structure Info Saving: true
[10:14:09] [Server thread/INFO]: Max TNT Explosions: 100
[10:14:09] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:14:09] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:14:09] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:14:09] [Server thread/INFO]: Random Lighting Updates: false
[10:14:09] [Server thread/INFO]: Sending up to 10 chunks per packet
[10:14:09] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:14:09] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:14:09] [Server thread/INFO]: Mob Spawn Range: 4
[10:14:09] [Server thread/INFO]: Anti X-Ray: true
[10:14:09] [Server thread/INFO]: 	Engine Mode: 1
[10:14:09] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:14:09] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[10:14:09] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:14:09] [Server thread/INFO]: Max Entity Collisions: 8
[10:14:09] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:14:09] [Server thread/INFO]: -------- World Settings For [Spawn] --------
[10:14:09] [Server thread/INFO]: Fix TNT cannons: false
[10:14:09] [Server thread/INFO]: Water over lava flow speed: 5
[10:14:09] [Server thread/INFO]: World async lighting: false
[10:14:09] [Server thread/INFO]: WorldServer TickNextTick cap set at 10000
[10:14:09] [Server thread/INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:14:09] [Server thread/INFO]: Keep spawn chunk loaded: true
[10:14:09] [Server thread/INFO]: Allow undead horse types to be leashed: false
[10:14:09] [Server thread/INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:14:09] [Server thread/INFO]: Player blocking damage multiplier set to 0.5
[10:14:09] [Server thread/INFO]: Remove invalid mob spawner tile entities: true
[10:14:09] [Server thread/INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:14:09] [Server thread/INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[10:14:09] [Server thread/INFO]: Preparing start region for level 0 (Seed: 0)
[10:14:09] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9
[10:14:09] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[10:14:09] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[10:14:09] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:14:09] [Server thread/INFO]: Done (0.517s)! For help, type "help" or "?"
[10:14:09] [Server thread/INFO]: Timings Reset
[10:14:16] [Server thread/INFO]: Stopping the server
[10:14:16] [Server thread/INFO]: Stopping server
[10:14:16] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v6.1.9;caf0ad9
[10:14:16] [Server thread/INFO]: Saving players
[10:14:16] [Server thread/INFO]: Saving worlds
[10:14:16] [Server thread/INFO]: Saving chunks for level 'Spawn'/Overworld
`

**Comment by jan5326** [comment]
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/4689649/latest.log)

**Comment by jan5326** [comment]
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/4689727/latest.log)

**Comment by jan5326** [comment]
This is what console shows that the logs don't. 
[console.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4689751/console.txt)

**Comment by SBPrime** [comment]
This is spigot 1.8?

**Comment by jan5326** [comment]
I'm Using Paper-443 (most recent 1.8.8 ver) which is a fork of Spigot 1.8 so yes?

Also apologies for not putting this in the AWE premium repository issues. I didn't realize there was one, because I was directed to here by pressing 'Ask questions / Get support' on the AWE Prem spigot page

**Comment by HeslopDawg** [comment]
Waiting for a answer as well.

**Comment by SBPrime** [comment]
Sorry, for some reasons my answer was not saved:
For Minecraft 1.12 and older please use old version 3.5.4 and WE 6.1.7.3.
