### ISSUE TITLE
1.15.2 Spigot

### ISSUE THREAD

**Issue by 1337god** [SBPrime/AsyncWorldEdit#328]
```[10:17:12] [Server thread/ERROR]: Error occurred while enabling AsyncWorldEdit v3.7.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/history/change/BiomeChange3D
        at org.primesoft.asyncworldedit.changesetSerializer.serializers.SerializerBiomeChange3D.<clinit>(SerializerBiomeChange3D.java:71) ~[?:?]
        at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.initialize(SerializerManager.java:167) ~[?:?]
        at org.primesoft.asyncworldedit.changesetSerializer.SerializerManager.<init>(SerializerManager.java:161) ~[?:?]
        at org.primesoft.asyncworldedit.core.AsyncWorldEditCore.onEnable(AsyncWorldEditCore.java:345) ~[?:?]
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onEnable(AsyncWorldEditBukkit.java:306) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-375]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Paper-375]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-375]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.history.change.BiomeChange3D
        at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.primesoft.asyncworldedit.Loader.loadClass(Loader.java:193) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 13 more
[10:17:12] [Server thread/INFO]: [AsyncWorldEdit] Disabling AsyncWorldEdit v3.7.3```

**Comment by 1337god** [comment]
What's the recommended World Edit version I should use for 1.15.2 Spigot?

**Comment by SBPrime** [comment]
You are using an incompatible version of WE. Please check plugin release notes. As a rule: use the latest version of AWE + the WE that is in the release notes.
