### ISSUE TITLE
Console error - cannot start plugin

### ISSUE THREAD

**Issue by dkim19375** [SBPrime/AsyncWorldEdit#360]
Hello, I am using AWE 3.6.20 free version, and I cannot start the plugin on a 1.8.8 paper server. Anyone know why?
```
[11:07:19] [Server thread/ERROR]: Could not load 'plugins\AsyncWorldEdit-3.6.20.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.IllegalStateException: Unable to get loaders.
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:115) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:100) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.util.List (java.util.LinkedHashMap and java.util.List are in module java.base of loader 'bootstrap')
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:113) ~[?:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:124) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:100) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
```

**Comment by dkim19375** [comment]
closing - it looks like the free version doesn't receive support :/

**Comment by SBPrime** [comment]
Check the release notes for latest free version and follow the instructions for  MC 1.12.

**Comment by dkim19375** [comment]
Thanks so much! :)
