### ISSUE TITLE
Console Error on Paper 1.16.5 after Server Shutdown

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [SBPrime/AsyncWorldEdit#375]
Paper 1.16.5
latest.log: https://gist.github.com/PiggiesGoSqueal/1d1920bed55d50239c870dcd688443de

Console Error on Paper 1.16.5 after Server Shutdown
`[14:13:42 INFO]: [AsyncWorldEdit] Disabling AsyncWorldEdit v3.8.3
[14:13:42 INFO]: [AsyncWorldEdit] Unloading plugins...
[14:13:42 ERROR]: Exception stopping the server
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:177) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:146) ~[patched_1.16.5.jar:git-Paper-670]
        at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.sendError(RollbarErrorReporter.java:185) ~[?:?]
        at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter$GlobalExceptionFilter.isLoggable(RollbarErrorReporter.java:332) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:965) ~[?:?]
        at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.handlePluginException(SimplePluginManager.java:563) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:518) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Paper-670]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:898) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:746) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1174) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-670]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by PiggiesGoSqueal** [comment]
Perhaps I accidentally downloaded free version instead of premium version- idk.

**Comment by PiggiesGoSqueal** [comment]
I downgraded 1 version for Premium & it solved it.

**Comment by SBPrime** [comment]
Can you share a longer log? Initially I thought that it is related to something else, but it looks like something new.

**Comment by cammygames** [comment]
This of any use? https://pastebin.com/6sDFSvq1

**Comment by SBPrime** [comment]
Thx. The plugin did not start properly thats most likely why you had an error.
The issue was already reported and solved. I'm going to close it as duplicate of #376
