### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by Dqgs** [SBPrime/AsyncWorldEdit#380]
https://mcpaste.io/932c57bc9407b45e

**Comment by SBPrime** [comment]
The error is from core protect:
```
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/logging/AbstractLoggingExtent
at net.coreprotect.worldedit.CoreProtectEditSessionEvent.wrapForLogging(CoreProtectEditSessionEvent.java:45) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
... 53 more
```

Are you sure that you setup the plugin correctly?

Please provide full server startup log and log for a single block change with AWE set to debug mode.

**Comment by SBPrime** [comment]
No response.
