### ISSUE TITLE
3.9.1 Won't load

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#399]
Whatever I do, I can't get AWE 3.9.1 to load properly
The startup log:
```
[15:15:51 ERROR]: Could not load 'plugins/AsyncWorldEdit-3.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.jar:git-Paper-66]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.jar:git-Paper-66]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.jar:git-Paper-66]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.jar:git-Paper-66]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-66]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192) ~[?:?]
at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.cleanPlugin(ClassLoaderHelper.java:200) ~[?:?]
at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:99) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:466) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.jar:git-Paper-66]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.jar:git-Paper-66]
... 7 more
```
Java 16
Paper 1.17 build 66
WE 7.2.6 (and 7.2.5)
AWE 3.9.1 and AWE-premium 3.9.1

**Comment by SBPrime** [comment]
Looks like you are using an unsupported WE. Please send the full log.

On my end I tested with:
```
> version
[20:47:53 INFO]: Checking version, please wait...
[20:47:53 INFO]: This server is running Paper version git-Paper-66 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 31d8fd5)
You are running the latest version
Previous version: git-Paper-593 (MC: 1.16.5)
> we version
[20:48:56 INFO]: WorldEdit — wersja: 7.3.0-SNAPSHOT
[20:48:56 INFO]: https://github.com/EngineHub/WorldEdit/
[20:48:56 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.3.0-SNAPSHOT+5836-183ae4a)

[20:48:56 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

> version asyncworldedit
[20:50:32 INFO]: AsyncWorldEdit version 3.9.1
```

No issues. Obviously to make sure that I uploaded the proper jar I used AWE downloaded from spigot.

**Comment by x1p** [comment]
Currently I use this WE version:
```
we version
[22:29:45 INFO]: WorldEdit version 7.2.6-SNAPSHOT
[22:29:45 INFO]: https://github.com/EngineHub/WorldEdit/
[22:29:45 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.2.6-SNAPSHOT+5844-728a152)
[22:29:45 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```
I thought I had the right one. Full log: https://pastebin.com/NfMTLeWz

Just tested with WE 7.3.0 build 5836. Full log: https://pastebin.com/nE8ezCyB

**Comment by x1p** [comment]
Found the culprit.
The SysoutCatcher was colliding somehow. That is only for testing things.
Fixed then.

**Comment by Draycia** [comment]
In the future please let me know, I can't fix issues I do not know about.
I'll submit a fix to the plugin soon, paper has already submitted a fix to their impl.

**Comment by x1p** [comment]
@Draycia
I had this issue using SysoutCatcher 1.0.1. After I had found out that this conflicted with AWE, I checked the spigot page of SysoutCatcher. I found out that I had missed a few updates. I either never got a notification or I dismissed it. So I thought I was my own mistake. I then didn't check to see if the current version didn't conflicted. I was already glad that I could update and use AWE further.
So it's my bad.
I just tested with the more recent version 1.1.2 and AWE loaded fine with this one.
Believe it or not: 1.2.0 however won't.
<details>
  <summary>Serverlog AWE + Sysout 1.0.2, click to open</summary>
  
 ```
[12:04:04] [Server thread/ERROR]: [[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:04:15] [Server thread/WARN]: Legacy plugin NightVisionReloaded v1.7 does not specify an api-version.
[12:04:15] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-3.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1310]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192) ~[AsyncWorldEdit-3.9.1.jar:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.cleanPlugin(ClassLoaderHelper.java:200) ~[AsyncWorldEdit-3.9.1.jar:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:99) ~[AsyncWorldEdit-3.9.1.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1310]
	... 7 more
[12:04:15] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.47
[12:04:15] [Server thread/INFO]: [SysoutCatcher] Loading SysoutCatcher v1.0.1
 ```
 
 </details>
 
 <details>
  <summary>Serverlog AWE + Sysout 1.1.2, click to open</summary>
  
 ```
[12:02:04] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[12:02:05] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2193ms)
[12:02:05] [Server thread/INFO]: [SysoutCatcher] Enabling SysoutCatcher v1.1.2
[12:02:05] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[12:02:05] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[12:02:05] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[12:02:05] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[12:02:05] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.1-SNAPSHOT-b531
[12:02:05] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[12:02:05] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.6-beta-02+2e45a20
[12:02:05] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[12:02:05] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[12:02:06] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2 as the Bukkit adapter
[12:02:08] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.9.1
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] Platform set to Bukkit API
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] ===================================================================================
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =     ___                         _       __           __    ________    ___ __   =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =    /   |  _______  ______  ____| |     / /___  _____/ /___/ / ____/___/ (_) /_  =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =   / /| | / ___/ / / / __ \/ ___/ | /| / / __ \/ ___/ / __  / __/ / __  / / __/  =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =  / ___ |(__  ) /_/ / / / / /__ | |/ |/ / /_/ / /  / / /_/ / /___/ /_/ / / /_    =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] = /_/  |_/____/\__, /_/ /_/\___/ |__/|__/\____/_/  /_/\__,_/_____/\__,_/_/\__/    =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =             /____/                                                              =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] = Author: SBPrime                                                                 =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] =                                                                                 =
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] ===================================================================================
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] Initializing WorldEdit.
[12:02:09] [AWE:Cron:undoCleanup/INFO]: [AsyncWorldEdit] Undo cleanup started...
[12:02:09] [AWE:Cron:undoCleanup/INFO]: [AsyncWorldEdit] ...undo cleanup done.
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] No matching adapter found for Bukkit.v1_17_R1, DirectChunkAPI disabled
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix.
[12:02:09] [Server thread/INFO]: [AsyncWorldEdit] Enabled
[12:02:09] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

 ```
 
 </details>
 
 <details>
  <summary>Serverlog AWE + Sysout 1.2.0, click to open</summary>
  
 ```
[12:10:43] [Server thread/INFO]: [SysoutCatcher] Paper SysoutCatcher found! Disabling plugin's sysout handling.
[12:10:43] [Server thread/INFO]: [SysoutCatcher] SysoutCatcher (plugin) will continue to reroute Bukkit.getLogger() logs!
[12:10:43] [Server thread/ERROR]: [[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:10:52] [Server thread/WARN]: Legacy plugin NightVisionReloaded v1.7 does not specify an api-version.
[12:10:52] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-3.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1310]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1310]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192) ~[AsyncWorldEdit-3.9.1.jar:?]
	at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.cleanPlugin(ClassLoaderHelper.java:200) ~[AsyncWorldEdit-3.9.1.jar:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:99) ~[AsyncWorldEdit-3.9.1.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Purpur-1310]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1310]
	... 7 more
[12:10:53] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.47
[12:10:53] [Server thread/INFO]: [SysoutCatcher] Loading SysoutCatcher v1.2.0
 ```
 
 </details>

**Comment by Draycia** [comment]
Have you updated paper? The fix on their end was pushed last night. My plugin doesn't override paper's impl.

**Comment by Draycia** [comment]
Make sure you're on paper build 155 or later.

**Comment by x1p** [comment]
I'm indeed just behind that build as Purpur is usually a day or 2 behind.
