### ISSUE TITLE
AWE doesn't work on 1.8

### ISSUE THREAD

**Issue by andreasdc** [SBPrime/AsyncWorldEdit#414]
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v3.5.2
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.ForwardExtentCopy injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.FlattenedClipboardTransform injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SnapshotUtilCommands injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat injected.
[17:47:28] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled
[17:47:28] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.5.4
[17:47:28] [Server thread/ERROR]: Error occurred while enabling AsyncWorldEdit v3.5.4 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @37c0dafa
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at org.primesoft.asyncworldedit.utils.Reflection.invoke(Reflection.java:118) ~[?:?]
	at org.primesoft.asyncworldedit.Loader.findLoadedClass(Loader.java:365) ~[?:?]
	at org.primesoft.asyncworldedit.Loader.loadClass(Loader.java:194) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onEnable(AsyncWorldEditBukkit.java:246) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:396) [spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:378) [spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:335) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:214) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:661) [spigot.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[17:47:28] [Server thread/INFO]: [AsyncWorldEdit] Disabling AsyncWorldEdit v3.5.4
[17:47:28] [Server thread/INFO]: [AsyncWorldEdit] Disable

**Comment by SBPrime** [comment]
Java 9+ is not supported for old versions of AWE.

**Comment by andreasdc** [comment]
> Java 9+ is not supported for old versions of AWE.
> 
> Please use: --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED

[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v3.5.2
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.ForwardExtentCopy injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.FlattenedClipboardTransform injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SnapshotUtilCommands injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat injected.
[00:21:51] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.5.4
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to invoke findLoadedClass: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Unable to create AWE Core: unsupported version.
[00:21:51] [Server thread/INFO]: [AsyncWorldEdit] Enabled

How to check if the plugin works?

**Comment by andreasdc** [comment]
@SBPrime it still lags the whole server and uses a lot of memory.
