### ISSUE TITLE
Problems with Crucible

### ISSUE THREAD

**Issue by Zilacon** [SBPrime/AsyncWorldEdit#420]
Ive been struggling to get this to work for hours...
Ive downloaded 2.3.3 and put it in my plugins folder
Placed the Injector into the mods folder
Downloaded WorldEdit Forge 6.0 Beta 1 and place it into the mods folder
Downloaded WorldEdit Bukkit 6.0 Beta 1 and place it into the plugins folder
Start server
Everything explodes

Cant even use wand:
```
[17:13:28 INFO]: Zilacon issued server command: //wand
[17:13:28 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@381c65fd to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[EventHandler.class:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [EventBus.class:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [EventBus.class:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.0-beta-01.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.0-beta-01.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) [SimpleCommandMap.class:1.7.10-5.0-master-f045cf2]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:699) [CraftServer.class:1.7.10-5.0-master-f045cf2]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1372) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1109) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:826) [?:1.8.0_312]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[MethodEventHandler.class:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[EventHandler.class:?]
        ... 17 more
Caused by: java.lang.AbstractMethodError: com/sk89q/worldedit/util/command/CommandCallable.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Z
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:225) ~[CommandManager.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[MethodEventHandler.class:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[EventHandler.class:?]
        ... 17 more
```

It says it cant find the injector, when its clearly in the mods folder:
[17:08:00 INFO]: [AsyncWorldEdit] AsyncWorldEditInjector plugin not found, trying to initialize using static instances...

[17:08:00 WARN]: [WorldEdit] Multiple ports of WorldEdit are installed but they report different versions (6.0-beta-01 and 6.0-beta-01;3335-e7a18b26). If these two versions are truly different, then you may run into unexpected crashes and errors.
[17:08:00 INFO]: [WorldEdit] Logging WorldEdit commands to /home/apoc/Servers/1710-Servers/GP/plugins/WorldEdit/worldedit.log
[17:08:00 INFO]: [WorldEdit] WorldEdit could not find a Bukkit adapter for this MC version, but it seems that you have another implementation of WorldEdit installed (Forge-Official) that handles the world editing.

How do i resolve this?

**Comment by SBPrime** [comment]
Sorry forge is not compatible. I'm keeping it open perhaps in the future I'll add support.
