### ISSUE TITLE
Problem in 1.6.4 minecraft version

### ISSUE THREAD

**Issue by SkiiM8** [SBPrime/AsyncWorldEdit#445]
Hello guys.
I have a problem, i install AWE on my 1.6.4 MCPC+ server, but it doesn't work. The plugin is detected, but when i use world edit to make a //paste, world edit don't "use" AWE. I use WE version 6.1, and AWE i tried version 1.2, but it's not working. And i'm not sure what version i have to use for 1.6.4 server.

So if someone have an idee, that could be great ! 

And don't tell me to not be in 1.6.4 cause i need to be in 1.6.4 x)

Edit : I don't know if this can help, but i don't have the asyncworldedit-injector.jar when i start my server, but i have config file.

Thanks !

**Comment by SkiiM8** [comment]
This is what i got in the server logs
```CSS
This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
2023-03-13 22:27:21 [INFO] [AsyncWorldEdit] World edit session not set to AsyncWorldedit. Fixing.
2023-03-13 22:27:21 [SEVERE] [WorldEdit] Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.

This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
2023-03-13 22:27:23 [INFO] [AsyncWorldEdit] World edit session not set to AsyncWorldedit. Fixing.
2023-03-13 22:27:23 [SEVERE] [WorldEdit] Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.

This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
2023-03-13 22:27:25 [INFO] [AsyncWorldEdit] World edit session not set to AsyncWorldedit. Fixing.
2023-03-13 22:27:25 [SEVERE] [WorldEdit] Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.

This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
2023-03-13 22:27:27 [INFO] [AsyncWorldEdit] World edit session not set to AsyncWorldedit. Fixing.
2023-03-13 22:27:27 [SEVERE] [WorldEdit] Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.

This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
2023-03-13 22:27:29 [INFO] [AsyncWorldEdit] World edit session not set to AsyncWorldedit. Fixing.
2023-03-13 22:27:29 [SEVERE] [WorldEdit] Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.

This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.



```

```CSS
2023-03-13 22:26:21 [INFO] Bukkit version format changed. Version not checked.
2023-03-13 22:26:21 [INFO] git-MCPC-Plus-jenkins-MCPC-Plus-164-251 (MC: 1.6.4)
2023-03-13 22:26:21 [INFO] 1.6.4-R2.1-SNAPSHOT
2023-03-13 22:26:22 [INFO] Essentials: Using GroupManager based permissions.
2023-03-13 22:26:22 [INFO] [EssentialsChat] Enabling EssentialsChat v2.12.2
2023-03-13 22:26:22 [INFO] [AsyncWorldEdit] Enabling AsyncWorldEdit v1.2
2023-03-13 22:26:23 [INFO] [AsyncWorldEdit] Your version of the plugin was not found on the plugin page. Your version: 1.2
2023-03-13 22:26:23 [INFO] [AsyncWorldEdit] Unable to inject LocalSession factory: unsupported WorldEdit version.
2023-03-13 22:26:23 [INFO] [AsyncWorldEdit] Unable to set logger: unsupported WorldEdit version.
2023-03-13 22:26:23 [INFO] [AsyncWorldEdit] vvvvvvvvvvvvvvvvv  Please ignore  vvvvvvvvvvvvvvvvv
2023-03-13 22:26:23 [SEVERE] Error occurred while enabling AsyncWorldEdit v1.2 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldedit.WorldEdit.<init>(Lcom/sk89q/worldedit/ServerInterface;Lcom/sk89q/worldedit/LocalConfiguration;)V
	at org.primesoft.asyncworldedit.worldedit.WorldEditProxy.<init>(WorldEditProxy.java:78)
	at org.primesoft.asyncworldedit.worldedit.WorldeditIntegrator.createWorldEditProxy(WorldeditIntegrator.java:143)
	at org.primesoft.asyncworldedit.worldedit.WorldeditIntegrator.<init>(WorldeditIntegrator.java:125)
	at org.primesoft.asyncworldedit.PluginMain.onEnable(PluginMain.java:171)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
```

**Comment by SkiiM8** [comment]
Alright guys problem solved
wrong world edit version
lol
