### ISSUE TITLE
async not loading with new paper, mc and world edit

### ISSUE THREAD

**Issue by GarretSidzaka** [SBPrime/AsyncWorldEdit#447]
```
mc  | [04:53:17 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'AsyncWorldEdit-3.9.4.jar' in folder 'plugins'
mc  | org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
mc  |   at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:504) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   at java.lang.Thread.run(Unknown Source) ~[?:?]
mc  | Caused by: java.lang.ExceptionInInitializerError
mc  |   at java.lang.Class.forName0(Native Method) ~[?:?]
mc  |   at java.lang.Class.forName(Unknown Source) ~[?:?]
mc  |   at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
mc  |   at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.1.jar:git-Paper-48]
mc  |   ... 9 more
mc  | Caused by: java.lang.IllegalStateException: Unable to get loaders.
mc  |   at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.getLoaders(ClassLoaderHelper.java:129) ~[AsyncWorldEdit-3.9.4.jar:?]
mc  |   at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.removeLoader(ClassLoaderHelper.java:138) ~[AsyncWorldEdit-3.9.4.jar:?]
mc  |   at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:100) ~[AsyncWorldEdit-3.9.4.jar:?]
mc  |   at java.lang.Class.forName0(Native Method) ~[?:?]

```

 minecraft server version 1.20.1
 This server is running Paper version git-Paper-48 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b34d4ec)

**Comment by GarretSidzaka** [comment]
bump?

**Comment by tajemniktv** [comment]
Yup, happens on my end to. Nearly fresh instance
