### ISSUE TITLE
java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory

### ISSUE THREAD

**Issue by frdmn** [SBPrime/AsyncWorldEdit#71]
_Informations_:

* Spigot: git-Spigot-5ead057-1a84bac (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
* WorldEdit: Bukkit-Official (6.0;3342-78f975b9)
* AsyncWorldEdit: 2.1.2 (latest)
* ProtocolLib: 3.6.3b72

_Error_:

    [20:23:50] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit_2.1.2.jar' in folder 'plugins'
    org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
    Caused by: java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/injector/classfactory/IClassFactory
      at java.lang.Class.forName0(Native Method) ~[?:1.7.0_65]
      at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      ... 6 more
    Caused by: java.lang.ClassNotFoundException: org.primesoft.asyncworldedit.injector.classfactory.IClassFactory
      at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_65]
      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_65]
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
      at java.lang.Class.forName0(Native Method) ~[?:1.7.0_65]
      at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-5ead057-1a84bac]
      ... 6 more

Thanks in advance!

**Comment by SBPrime** [comment]
You did not install the injector.

**Comment by frdmn** [comment]
@SBPrime You were right, thank you! Works like a charm!
