### ISSUE TITLE
Injector looks good but AsyncWorldEdit can't generate configuration file

### ISSUE THREAD

**Issue by MineMine** [SBPrime/AsyncWorldEdit#78]
this is part of my log 

Injector works fine

[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorForge
[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SchematicCommands injected.
[19:21:25] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.ScriptingCommands injected.

using same version of WorldEdit-bukkit and WorldEdit-forge (of course AWE is the same)

[19:22:57] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.0-beta-01;3335-e7a18b26
[19:22:57] [Server thread/INFO]: WEPIF: GroupManager detected! Using GroupManager for permissions.
[19:22:57] [Server thread/WARN]: [WorldEdit] Multiple ports of WorldEdit are installed but they report different versions (6.0-beta-01 and 6.0-beta-01;3335-e7a18b26). If these two versions are truly different, then you may run into unexpected crashes and errors.
[19:22:57] [Server thread/INFO]: [WorldEdit] WorldEdit could not find a Bukkit adapter for this MC version, but it seems that you have another implementation of WorldEdit installed (Forge-Official) that handles the world editing.

error appears at loading configuration file (or can't create config file)

[19:23:03] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v2.1.0
[19:23:03] [Server thread/INFO]: [AsyncWorldEdit] Error loading config

[19:23:37] [Server thread/INFO]: MineMine issued server command: /awe
[19:23:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'awe' in plugin AsyncWorldEdit v2.1.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1350) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1132) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.NullPointerException
	at org.primesoft.asyncworldedit.PlayerManager.findPlayer(PlayerManager.java:226) ~[?:?]
	at org.primesoft.asyncworldedit.PlayerManager.getPlayer(PlayerManager.java:179) ~[?:?]
	at org.primesoft.asyncworldedit.PlayerManager.getPlayer(PlayerManager.java:153) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditMain.onCommand(AsyncWorldEditMain.java:236) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	... 13 more
[19:23:39] [Server thread/WARN]: Unexpected exception while parsing console command "awe"
org.bukkit.command.CommandException: Unhandled exception executing command 'awe' in plugin AsyncWorldEdit v2.1.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:465) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:424) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.NullPointerException
	at org.primesoft.asyncworldedit.AsyncWorldEditMain.sayConsole(AsyncWorldEditMain.java:150) ~[?:?]
	at org.primesoft.asyncworldedit.PlayerEntry.say(PlayerEntry.java:95) ~[?:?]
	at org.primesoft.asyncworldedit.Help.ShowHelp(Help.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.AsyncWorldEditMain.onCommand(AsyncWorldEditMain.java:264) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	... 8 more

there is only three lines in config.yml (I don't know exactly who generate this letter)

plugin-channel: world_info
inform-player: false
encoding: UTF-8

**Comment by SBPrime** [comment]
Check if you have write permissions to the AWE plugin folder.

**Comment by MineMine** [comment]
I've already check the directory permission 

there is no permission problem in plugins folder 

only two plugins (ProtocolLib and AWE) can't create their own configuration file 

what should i do?

**Comment by SBPrime** [comment]
To help me diagnose the problem please send:
1. Go to the plugins folder
2. send output of: "id -u -n"
3. send output of: "ls -l"

To solve the problem try manually creating the AsyncWorldEdit directory then extract the config.yml from AsyncWorldEdit.jar and put it into that folder.

**Comment by SBPrime** [comment]
Did you manage to fix the problem?

**Comment by SBPrime** [comment]
No answer, unable to reproduce.
