### ISSUE TITLE
MultiversePortals Internal error (Spigot 1.8)

### ISSUE THREAD

**Issue by SiMPaST** [SBPrime/AsyncWorldEdit#83]
Everytime I try to create a portal by using '/mvp create' I get the message 'An internal error occured while attempting to perform this command'.
The server log with the error is posted below (I posted the whole log because I don't really know if there is somthing important before the part discribing the error).
I use the 1.8 version of Spigot for my server and have installed following plugins:
xInventories, Multiverse-Core, Multiverse-Portals, BetterEnderChest and Essentials

All solutions I found up to now don't work for me since I don't use WorldEdit (which caused the problem in all the other cases).

I hope someone can help me here, finaly. I'm serching for a solution since beginning of january ;)  
Thank you for any answer. 

[17:19:44] [Server thread/INFO]: Starting minecraft server version 1.8
[17:19:44] [Server thread/INFO]: Loading properties
[17:19:44] [Server thread/INFO]: Default game type: SURVIVAL
[17:19:44] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-e497721-a1ce164 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[17:19:44] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:19:44] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:19:44] [Server thread/INFO]: Debug logging is disabled
[17:19:44] [Server thread/INFO]: Generating keypair
[17:19:45] [Server thread/INFO]: Starting Minecraft server on 85.131.157.137:25565
[17:19:45] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[17:19:45] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b692
[17:19:45] [Server thread/INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5-b713
[17:19:45] [Server thread/INFO]: [Essentials] Loading Essentials vTeamCity
[17:19:45] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[17:19:45] [Server thread/INFO]: Preparing level "world"
[17:19:45] [Server thread/INFO]: -------- World Settings For [world] --------
[17:19:45] [Server thread/INFO]: Mob Spawn Range: 4
[17:19:45] [Server thread/INFO]: Anti X-Ray: true
[17:19:45] [Server thread/INFO]: 	Engine Mode: 1
[17:19:45] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:19:45] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[17:19:45] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:19:45] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:19:45] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:19:45] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:19:45] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:19:45] [Server thread/INFO]: Random Lighting Updates: false
[17:19:45] [Server thread/INFO]: Structure Info Saving: true
[17:19:45] [Server thread/INFO]: Sending up to 10 chunks per packet
[17:19:45] [Server thread/INFO]: Max Entity Collisions: 8
[17:19:45] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:19:45] [Server thread/INFO]: Max TNT Explosions: 100
[17:19:45] [Server thread/INFO]: Item Merge Radius: 2.5
[17:19:45] [Server thread/INFO]: Item Despawn Rate: 6000
[17:19:45] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:19:45] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:19:45] [Server thread/INFO]: View Distance: 8
[17:19:45] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:19:45] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:19:45] [Server thread/INFO]: Clear tick list: false
[17:19:45] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:19:45] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[17:19:45] [Server thread/INFO]: Mob Spawn Range: 4
[17:19:45] [Server thread/INFO]: Anti X-Ray: true
[17:19:45] [Server thread/INFO]: 	Engine Mode: 1
[17:19:45] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:19:45] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[17:19:45] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:19:45] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:19:45] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:19:45] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:19:45] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:19:45] [Server thread/INFO]: Random Lighting Updates: false
[17:19:45] [Server thread/INFO]: Structure Info Saving: true
[17:19:45] [Server thread/INFO]: Sending up to 10 chunks per packet
[17:19:45] [Server thread/INFO]: Max Entity Collisions: 8
[17:19:45] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:19:45] [Server thread/INFO]: Max TNT Explosions: 100
[17:19:45] [Server thread/INFO]: Item Merge Radius: 2.5
[17:19:45] [Server thread/INFO]: Item Despawn Rate: 6000
[17:19:45] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:19:45] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:19:45] [Server thread/INFO]: View Distance: 8
[17:19:45] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:19:45] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:19:45] [Server thread/INFO]: Clear tick list: false
[17:19:45] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:19:45] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[17:19:45] [Server thread/INFO]: Mob Spawn Range: 4
[17:19:45] [Server thread/INFO]: Anti X-Ray: true
[17:19:45] [Server thread/INFO]: 	Engine Mode: 1
[17:19:45] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:19:45] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[17:19:45] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:19:45] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:19:45] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:19:45] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:19:45] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:19:45] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:19:45] [Server thread/INFO]: Random Lighting Updates: false
[17:19:45] [Server thread/INFO]: Structure Info Saving: true
[17:19:45] [Server thread/INFO]: Sending up to 10 chunks per packet
[17:19:45] [Server thread/INFO]: Max Entity Collisions: 8
[17:19:45] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:19:45] [Server thread/INFO]: Max TNT Explosions: 100
[17:19:45] [Server thread/INFO]: Item Merge Radius: 2.5
[17:19:45] [Server thread/INFO]: Item Despawn Rate: 6000
[17:19:45] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:19:45] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:19:45] [Server thread/INFO]: View Distance: 8
[17:19:45] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:19:45] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:19:45] [Server thread/INFO]: Clear tick list: false
[17:19:45] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:19:46] [Server thread/INFO]: Preparing start region for level 0 (Seed: 2275712042708361083)
[17:19:47] [Server thread/INFO]: Preparing spawn area: 4%
[17:19:48] [Server thread/INFO]: Preparing spawn area: 61%
[17:19:49] [Server thread/INFO]: Preparing start region for level 1 (Seed: 7258170238870959244)
[17:19:50] [Server thread/INFO]: Preparing start region for level 2 (Seed: 7258170238870959244)
[17:19:51] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b692
[17:19:51] [Server thread/INFO]: [Multiverse-Core] [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b692
[17:19:53] [Server thread/INFO]: [Multiverse-Core] 3 - World(s) loaded.
[17:19:53] [Server thread/INFO]: [Multiverse-Core] Version 2.5-b692 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--
[17:19:53] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5-b713
[17:19:53] [Server thread/INFO]: [Multiverse-Portals] - Version 2.5-b713 Enabled - By Rigby and fernferret
[17:19:53] [Server thread/INFO]: [MVPLogging] 0 - Portals(s) loaded
[17:19:53] [Server thread/INFO]: [Essentials] Enabling Essentials vTeamCity
[17:19:53] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[17:19:53] [Server thread/INFO]: git-Spigot-e497721-a1ce164 (MC: 1.8)
[17:19:53] [Server thread/INFO]: 1.8-R0.1-SNAPSHOT
[17:19:53] [Server thread/INFO]: Using locale en_US
[17:19:53] [Server thread/INFO]: Using locale en_US
[17:19:53] [Server thread/INFO]: Essentials: Using config file enhanced permissions.
[17:19:53] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
[17:19:53] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:19:54] [Server thread/INFO]: Done (8.579s)! For help, type "help" or "?"
[17:19:54] [Server thread/INFO]: Starting GS4 status listener
[17:19:54] [Server thread/INFO]: Setting default query port to 25565
[17:19:54] [Query Listener #1/INFO]: Query running on 85.131.157.137:25565
[17:19:54] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[17:19:54] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b692 generated an exception while executing task 3
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
	at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
	at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[17:20:18] [Server thread/INFO]: Saving...
[17:20:18] [Server thread/INFO]: Saved the world
[17:21:18] [User Authenticator #1/INFO]: UUID of player JorKoe is 6d20a4ac-823c-4351-992c-4cd2eeafd8e1
[17:21:18] [Server thread/INFO]: JorKoe[/84.189.119.30:62614] logged in with entity id 130 at ([world] 449.5098916703711, 59.0, 108.5542789471819)
[17:21:29] [Server thread/INFO]: JorKoe issued server command: /mvp create Portal1
[17:21:39] [Server thread/INFO]: JorKoe issued server command: /gamemode 1
[17:21:51] [Server thread/INFO]: JorKoe issued server command: /mvp create Portal1
[17:21:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b713
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-e497721-a1ce164]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:174) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:101) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:236) ~[?:?]
	at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126) ~[?:?]
	at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-e497721-a1ce164]
	... 14 more

**Comment by SBPrime** [comment]
This has nothing to do with AWE. Report the bug to the plugin author.
